### ISSUE TITLE
Resource editing disabled error message [staging 0.9.3.02]

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#102]
![image](https://user-images.githubusercontent.com/51859157/210194211-4c753693-c7c8-4fba-befe-e76d2d305c38.png)
I'm still having this error pop up and it's happening more frequently especially if switching from one map to another.
I'm just switching between maps nothing odd or weird.  In this case I was trying to load sci_lowerhospital.  
I've been working w/ Hab_Airport and Tech_Hub though. So I have seen it with those maps too.  

I'm on staging 0.9.3.02  since it's release last week.

**Comment by MattFiler** [comment]
Thanks for separating into a new issue - this is indeed different to the previously fixed #91.

I'll take a look!

**Comment by ghramsey** [comment]
Thank you.  I'm not sure if it's actually doing what it says about editing disabled.  
I've been purposely exiting and restarting the script editor each time I see the error.
Just to be certain it's not borking anything.

**Comment by MattFiler** [comment]
Yeah it should all work fine without it, you just won't be able to edit any resources connected to entities like models/materials.

**Comment by MattFiler** [comment]
Turned out to be a 32-bit memory issue. I'm now favouring 64-bit (and using some new parsers), so this should be fixed!
