### ISSUE TITLE
"P:/CONTENT/..." automatically expanded when loading Level (minor bug)

### ISSUE THREAD

**Issue by Oliver2Goetz** [MattFiler/OpenCAGE#104]
When loading a level in the Cathode Editor the level entrypoint is already expanded.
![image](https://user-images.githubusercontent.com/44117499/210290166-e9631173-d447-4601-8c0e-6dbb11ce7a3b.png)

Not 100% sure if that really is a bug or intended in the new update. Nonetheless it's very minor.

**Comment by MattFiler** [comment]
This is a feature. When you load the PAK the root composite will be auto selected, and expanded in the list.
