### ISSUE TITLE
Encountered an issue while looking up entity!"

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#121]
![image](https://user-images.githubusercontent.com/51859157/210908114-0a6b621e-1ef1-44a5-9f62-65e0d75d88a5.png)
![image](https://user-images.githubusercontent.com/51859157/210908127-cd690492-d89b-4c57-bc44-8eb5fa877bef.png)

Got this in new staging update 0.9.3.3

**Comment by MattFiler** [comment]
Thanks for the report - consolodating this to #122

**Comment by MattFiler** [comment]
As posted in #122 - this should now be fixed on the staging branch :)
