### ISSUE TITLE
Entity lookup failed

### ISSUE THREAD

**Issue by Oliver2Goetz** [MattFiler/OpenCAGE#122]
I try to lookup an entity but I get this error:
![image](https://user-images.githubusercontent.com/44117499/210908432-87d29241-6e5b-4480-b45c-b66cba6e4902.png)

To my testing this only comes when I try to lookup an entity of type CAGEAnimation

Replicatable in the vanilla PAK for `ENG_TOWPLATFORM` in the composite `SCRIPT_STORYMISSION\M33_SHOWDOWN\M33_PART_01\M33_PT01`.
Entity example like in the screenshot is `M33_SC03`

**Comment by MattFiler** [comment]
Thanks for the report, I'll take a look after work today.

**Comment by MattFiler** [comment]
Should now be fixed on the staging branch :)
