### ISSUE TITLE
Proxies do not always function

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#123]
I have a triggerbox in Tech_hub, M3 to spawn aliens on the transit platform.  This works fine.  
I want to use this triggerbox to also open the transit office door which I've created a proxy to.

For some reason using on_entered >door_sml_2(proxy) >unlock_door in this fashion does not work.

I created a different triggerbox at the top of the ramp by the door with same commands and the 
door opened right up.  Any idea why one triggerbox opens the door but the other does not?

The only significant difference is open_on_reset is set by default on a new triggerbox.  
The old one has this unchecked. I checked it though and it made no difference the door still failed to open.
For now I'll just use the new triggerbox and move on. It works.  But it's strange and seems inconsistent.

Additionally,  you've added a checkbox to add default parameters.  
For a triggerbox it adds a float for on_entered, on_exited, boolean for enable_on_reset and a half_dimension box, 
but not one for transfom.   Is that correct?   I know you had a bug in that before.

**Comment by MattFiler** [comment]
Hey - this is an issue with proxies. There is an additional checksum value that I am still looking into - for some reason sometimes it works and others it doesn't. The same goes for overrides unfortunately.

**Comment by ghramsey** [comment]
Ah! OK.    I'll just keep the triggerbox I created.

Something else that might be important. Could is also be a zoning issue?  

I'm not 100% sure where the triggerbox that is not tripping the door is located.   It triggers as I'm inside the tram car. 
I took the coordinates from another mod that has aliens spawn in the transit station.  Was no need to reinvent the
wheel since that worked, but maybe that is complicating the proxy issue.

**Comment by MattFiler** [comment]
I believe this should be fixed in the staging branch when adding new proxies in. Please give it a go and let me know if you have any issues!

**Comment by ghramsey** [comment]
OK.  I'll try this out soon.

**Comment by ghramsey** [comment]
Yes. It now opens the transit office and upper lobby kitchen doors via proxy.

I moved the triggerbox location to the tram threshold.  
I found that it was not triggering at all. I do not know exactly where it was. 
I thought it was inside the tram at spawn  and the source of the alien and drois 
spawning  but the coordinates actually didn't match.

I had spawn_on_reset enabled for both so that was overriding the trigger.
 With those settings unchecked the entity spawn was not working.  
 Now with the triggerbox moved they spawn and the doors open via proxy.  

I seem to be required to use enable_on_reset on the triggerbox still or it fails to work.
I'm not sure when I'm supposed to use or not use that option, but this is a case of must.

**Comment by MattFiler** [comment]
Ayy, glad it's working now.

In regard to giving you an actual "how-to" of how to set up proxies, I'm afraid you're kinda on your own. The only commonality I noticed with them is that they always seem to have the same default parameters populated, so I implemented the defaults into the script editor. In terms of how to actually utilise them, I've not really dug too much into it.

It has been an ongoing confusion for me the difference between overrides and proxies, and wether proxies have anything special about them other than being able to reference entities across any composite (whereas overrides can only reference child composites). Either ways, I think if you're working on more complex scripts, proxies will be a very useful tool to be able to listen to events and trigger things across composites!

I'll be super interested to hear what you find out from digging around - I haven't really had much time to look into them other than fixing this bug :)

**Comment by MattFiler** [comment]
To clarify:

- An override is an overwrite of parameters on entities found within child composites of the current composite. Think of it like overriding a value on a prefab in Unity, if you've used that before.
- A proxy is a bridge to an entity in another composite in the context of the execution of the COMMANDS.PAK. You can use them to listen to and trigger events.

My confusion stems from the fact that I today noticed that proxies can provide parameters as well as links for events, and overrides can provide links for events as well as just parameter overrides. This blurs the line between the two considerably.

The fact remains that proxies will be useful for cross-composite scripting, but yeah just found that a surprising discovery!
