### ISSUE TITLE
Unable to edit VariableEntity

### ISSUE THREAD

**Issue by Oliver2Goetz** [MattFiler/OpenCAGE#125]
As already in the other issue (https://github.com/MattFiler/OpenCAGE/issues/124) I created a new VariableEntity:
![image](https://user-images.githubusercontent.com/44117499/211124793-af0fe450-e1c7-455c-a072-02812e902df3.png)
![image](https://user-images.githubusercontent.com/44117499/211124782-947edd93-09d3-43f9-974d-36f5dfc693fc.png)

Adding or removing a parameter is not possible. Duplicating or renaming the VariableEntity is also disabled.
I'm not exactly sure if that's an error here but not being able to rename the VariableEntity makes it so we have to name the entity like we want the parameter to be named.

**Comment by MattFiler** [comment]
Support for renaming variable entities is not currently added, will add today!

**Comment by MattFiler** [comment]
This will be pushed to the staging branch shortly.
