### ISSUE TITLE
HAB_Airport can get partially corrupted by just clicking the save button in Cathode editor

### ISSUE THREAD

**Issue by Const1702** [MattFiler/OpenCAGE#127]
I was doing modifications on the HAB_Airport level and noticed that when I load mission 2 or mission 11 the spacesuit stopped working properly. After pressing E to take off the suit it does show the animation, fades to black and just gets stuck on a black screen instead of fading back. I tried using a special tool that can remove screen effects to see what is going on, but the whole level is just black. Tried teleporting myself with a debug checkpoint, but no result. After trying to recreate the issue I noticed that by just clicking save without even doing anything breaks the spacesuit, so M2 and M11 become unplayable. To fix it I got rid of the old HAB_Airport and replaced it with the clean verified copy I have for cases like this.

**If you are trying to recreate this:** Load mission 2 (the one I tried this issue the most on) and check if it works. If it doesn't work, replace it with a clean copy and try again, so it works. After you made sure you have an original HAB_Airport level open Cathode editor and I recommend you make one modification on whatever entity you want and click save. Load M2 and try changing out of the spacesuit.

**OpenCAGE version: 0.9.3.30 (Staging)**
**Alien: Isolation opened from: STEAM** (Saying this, because some users use the Epic Games launcher and some use Steam)

**Comment by MattFiler** [comment]
Huh, good spot. I'll take a dig at this today.

**Comment by MattFiler** [comment]
A fix for this should now be in the staging branch :)
