### ISSUE TITLE
Entity link editor suggests wrong parameters

### ISSUE THREAD

**Issue by ttvjeffnl** [MattFiler/OpenCAGE#130]
also when adding a link pin out from a door composite it shows empty.
but when adding a link pin in it gives the correct parameters for the composite

![image](https://user-images.githubusercontent.com/68294929/211212515-36eb1178-948b-4cce-be8c-a63271e5c48d.png)
![image (1)](https://user-images.githubusercontent.com/68294929/211212518-c25e00a9-baf8-4fee-9f2e-1e41d46c339b.png)
![image (2)](https://user-images.githubusercontent.com/68294929/211212521-39b1103b-4d8d-4b0b-a492-b0f73bfc5baf.png)
![4](https://user-images.githubusercontent.com/68294929/211212753-e60e5bad-cc0b-4372-8f4a-b4694a536c31.png)

**Comment by MattFiler** [comment]
This should now be fixed in staging!
