### ISSUE TITLE
Unable to add TriggerSequence event triggers

### ISSUE THREAD

**Issue by Const1702** [MattFiler/OpenCAGE#132]
If I try to modify existing TriggerSequences I can see that the "Triggers" section shows all of the triggers that are connected to the sequence like in the picture:
![image](https://user-images.githubusercontent.com/116276106/211579043-49712e97-2a8c-4f00-b5e7-078b88d5f7a9.png)

But the new ones that I added don't show anything there even when they are connected to something:
![image](https://user-images.githubusercontent.com/116276106/211579286-4eb40087-daa1-4bc6-b4ee-b9d6c019c44c.png)

**OpenCAGE version: 0.9.3.4 (Staging)**

**Comment by MattFiler** [comment]
This is somewhat due to me still not fully understanding what the links in the "triggers" section do completely - they're some sort of event based on the progress of the sequence. Once they're understood, I'll add the ability to create/remove them (hence tagging as enhancement not bug!).

**Comment by MattFiler** [comment]
This is out now on staging!
