### ISSUE TITLE
Suggestion only: Button that opens a window showing the overrides and proxies that use the selected composite or that follow it through.

### ISSUE THREAD

**Issue by Const1702** [MattFiler/OpenCAGE#133]
A lot of composites' parameters are not only defined directly, but also with overrides. This can get tricky, because some overrides don't have a proper name and you have to look through every one of them until you see the entity it modifies. This can be made easier with some sort of window that shows two sections. For this example let's say we select an entity called RotateStripLight_42. In the two sections we see the overrides and proxies that:

**1. Interact with the entity directly. (Ex: RotateStripLight_42)**
**2. Don't exactly modify the entity, but follow it through. (Ex: RotateStripLight_42 -> RotateStripLight_Head)**

Using the items from the both sections you should be able to delete them directly from the window or have the ability to go to them so it takes you to the item (override or proxy) you selected back in the main window.

This could be useful for finding an entity's proxy in a storymission or changing some entity's sub-entity properties (Ex: RotateStripLight_42 -> **RotateStripLight_Head (Sub-entity)**.

This might be hard to add, seeing that you have issues with Override checksums and some entities' Overrides are defined in upper levels, so every time you open this window it will need to scan all of the composites in the whole level to locate any related Overrides and Proxies.

**Comment by MattFiler** [comment]
Agreed, this would be super useful! Will add when I get chance next :)

**Comment by MattFiler** [comment]
Added a new UI in on staging to show this - entities that are pointed to by an override or proxy will have this "references" button enabled:
![image](https://user-images.githubusercontent.com/6270995/215625757-c58b1f45-957d-47ce-b257-ec14884f9c71.png)


Clicking it will show this UI which allows you to jump to any of the overrides/proxies that point to the entity:
![image](https://user-images.githubusercontent.com/6270995/215625811-6675c8f9-1e96-43bc-81df-4cdb5ef4d9be.png)


I hope this is useful! Feel free to give any feedback before I push it through to main :)

**Comment by Const1702** [comment]
Thank you so much for adding this! For now it is functioning properly. I have noticed that after selecting entites it takes a long time to load their paramaters and while loading them the whole window freezes for ~2 seconds. I find this normal, because it is probably looking through the whole editor for overrides and proxies for the selected entity and if that is the case I would recommend for it to check for proxies and overrides after clicking the "References" button. That way you can scroll through items in the main list more faster.

I suggest that there is a checkbox in the "Linked Overrides and Proxies" window that stops it from closing after clicking "Jump to Override/Proxy", because when it closes and the entity has a lot of overrides I want to go back to that window to configure the other proxy/overrides. To do that I have to go back to in my case "AYZ\LIGHTS\SMALL_STRIP_ROTATE" and keep re-opening the window for each override. Here's an example with an entity with a lot of overrides:
![image](https://user-images.githubusercontent.com/116276106/215786480-5cfb2d3d-62cf-4f66-8019-0a5391e0563d.png)
It would be useful to be able to jump to a reference, configuring it and then just have the window already open and ready for the next one.

Hopefully you can get some rest first! Thank you again!

**Comment by MattFiler** [comment]
> I have noticed that after selecting entites it takes a long time to load their paramaters and while loading them the whole window freezes for ~2 seconds. 

Aware of this! It'll be sorted before I bring everything across to main, along with some other performance improvements.

> I suggest that there is a checkbox in the "Linked Overrides and Proxies" window that stops it from closing after clicking "Jump to Override/Proxy", because when it closes and the entity has a lot of overrides I want to go back to that window to configure the other proxy/overrides.

Nice idea.

**Comment by MattFiler** [comment]
Speed improvements are now in staging. Loading and saving of Commands should now be way quicker, along with selecting entities.

Please let me know if you have any issues!
