### ISSUE TITLE
Unable to find composite 7B-02-C0-75 on CHALLENGEMAP4

### ISSUE THREAD

**Issue by JulianAlien** [MattFiler/OpenCAGE#134]
![image](https://user-images.githubusercontent.com/117166040/211584530-4e3b5d54-2a74-4e33-b292-960908b3f2b7.png)
just do what OpenCAGE is telling me, just noticed this while scrolling through the Entries

**Comment by MattFiler** [comment]
This wasn't actually a bug with my tools but a bug with Creative Assembly's tools lol - they leave loads of deleted references in their scripting files, most of which I tidy up in my tools, but I missed this one. Have added a catch for it, thanks!
