### ISSUE TITLE
Suggestion only: Overrides should display more information in the main list

### ISSUE THREAD

**Issue by Const1702** [MattFiler/OpenCAGE#135]
Similar to #133

This seems easier to add than my last suggestion about overrides. I'm trying to locate some sub-entities of regular entities in a list, but that is not easy, because their parameters are stored in overrides with names like this **(F7-31-F5-76) F7-31-F5-76 (\*OVERRIDE\*)**. And for example to locate a "RotateStripLight"'s sub-entity RotateStripLight_Head with an override you have to look through all of the ones with obscure numbers and keep looking at the top right corner to see the actual entities they are connected to in the parameters section:
![TimeConsumingProblem](https://user-images.githubusercontent.com/116276106/212097666-ead8647b-027e-4e58-9636-bf0534278ae1.png)

What could be done instead is to keep the obscure names, but after **(\*OVERRIDE\*)** it should also display the entity which it is actually overriding. Like this:
**(F7-31-F5-76) F7-31-F5-76 (\*OVERRIDE\*) (RotateStripLight_8 -> RotateStripLight_Head)**

Having it shown like this in the main list will make searching for it easier and if it gets in your way while searching for composites there can be an option to filter it, _but that's for a future suggestion that I'm still not sure about posting which is related to sorting and filtering search results._

**Comment by MattFiler** [comment]
Just updated staging to present them like this:
![image](https://user-images.githubusercontent.com/6270995/215625505-de26e979-c384-4d61-a81c-09e51a069f8d.png)

Feels a lot better! I might go one step further eventually and list the overrides on the composite instance they're pointing to the children to to save them clogging up the entity list.

**Comment by Const1702** [comment]
Thank you! If you are thinking of making the overrides and proxies show only the child entity they are pointing to, without showing the full paths to prevent the list from being clogged up, I suggest that you make this a setting for the user to enable. For example: If we have an override going through Wall_5 -> TechWall_Light_B_1 it will only show TechWall_Light_B_1 (The child composite in this case) without showing "Wall_5" and that will affect searching for that specific light on that specific wall. Instead you will get a lot of TechWall_Light_B_1s and you won't know on which wall they are on unless you click on them and in a lot of levels walls are added a lot of times and a lot of them have lights with the same names so you will have to start looking through all overrides with the name TechWall_Light_B_1 to locate in this case "Wall_5". But this is only if you are planning on it showing only the child entities. The setting can be called something like "Show child components only for entity references in the entity list".
