### ISSUE TITLE
enhancement: housekeep extra entry boxes

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#149]
I'm not sure how to describe this;

When clicking on any of the settings to add parameter, add link out, remove, go to link, edit link, etc. ,
the program lets one click them over and over creating a new box for each.   

Seems like the program should do some housekeeping to keep multiple boxes being created to infinity. 
Maybe a limit on number of boxes or close all when an entry is created and saved.   They don't need to 
be modal, but surely it's not desired activity to make unlimited entry boxes.

On a system with low resources this might pose an issue since each box is added to the task bar.

**Comment by MattFiler** [comment]
I've just pushed out an update to staging that manages the lifetime of all popup windows, relative to when they would be useful. Please let me know your thoughts!
