### ISSUE TITLE
enhancement: pre-fill asset dropdown

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#158]
I would love improved prefills and more accurate prefills data type based on the parameter.

ENUMs for specific fuctions that really don't have any other possible entries.
Two that would be nice to prefill ENUM for Speech_Priority in the speech and speechscript functions.
When I select speech_priorty from the list of parameters on speech or speechscript it is an ENUM window.
I must then select SPEECH_PRIORTY from the list. Having this pre fill since it's obviously no other entry possible for that parameter.

Also, under the speechscript and speech functions having each parameter select the correct data type would be nice.
If I scroll through the list it will sometimes select the wrong type requiring deletion to correct.

Additionally, an autocomplete for long drop lists would help reduce scrolling and may help if 
there are a large amount of parameters, data types or ENUM . Even partial auto complete. 

I realize this adds complexity to the search stuff and may not be possible at this stage.

**Comment by MattFiler** [comment]
I've just pushed an update to staging that adds autocomplete for:
- Room reverbs
- Sound events
- Sound banks
- Materials
- UI strings
- Objective strings

I won't mark this ticket as completed yet, as I'll next look into supporting autocomplete for animations and skeletons, as well as better support for selecting enums.

**Comment by MattFiler** [comment]
Worth noting - I'm not entirely sure if all the values will be available for these dropdowns (particularly strings, as there's some filtering going on). Please let me know if you come across any instances where strings are referenced that don't appear in the dropdown :)

**Comment by ghramsey** [comment]
I was looking at this terminal_content and found a list that might be wrong: 
![image](https://user-images.githubusercontent.com/51859157/225175341-ca693104-c06c-465a-b21b-9005212cf1db.png)


The drop downlist on this entity shows all OBJ which doesn't match the default entry name thatis shown.
![image](https://user-images.githubusercontent.com/51859157/225175221-bfa48c56-d230-412c-9bd9-3b5ed6ffc0c8.png)

**Comment by MattFiler** [comment]
I'll take a look into the speech script one - RE the objective one, that is solved in the upcoming version :)

**Comment by ghramsey** [comment]
> I'll take a look into the speech script one - RE the termanal/objective one, that is solved in the upcoming update :)

The speech script is now possible a bug.   I saved edited scripts on the drop downs. When I saved and reloaded the changes were reverted.   The only way to be sure it didn't revert is to remove each line and regenerate them.

Grrrr.  I'm sorry my suggestion became a bug fix. :(

**Comment by MattFiler** [comment]
No probs :)

**Comment by MattFiler** [comment]
To keep this issue up-to-date: quite a few enum types are now populated in the staging build.

**Comment by MattFiler** [comment]
This has now been merged down to main, and I'm going to close this issue.

Enum population is still a WIP but ~70% are now known. Other asset types are now populated.

**Comment by MattFiler** [comment]
Re-opening this as it isn't technically completed. The current population progress has been merged down to main & is now live, however work remains to be completed for:
- ~20% of enums
- CMD_PlayAnimation skeletons/animations

**Comment by ghramsey** [comment]
Related to this enhancement and I guess it will be finished when Enums are being prefilled more fully. 

When setting a parameter such as  "speech priority" which it should become an enum type and go to the 
'speech priority' enum in the list.  For this specific instance using that type should always go to that enum 
as there are no other applicable data types in the list.

**Comment by ghramsey** [comment]
I think this is related to this enhancement.  I forget if there was an issue related to the dropdown lists as a bug.

The parameter 'reference' is globally missing from dropdown lists where it should be an option.  
In all cases it must be manually typed.  The screen shot is from a stock reference. 
Note how the word 'reference' is not highlighted in the list.

![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/db6c93d6-a4b1-4387-919c-38cc01070350)

I'm not sure if there's a technical reason for the parameter being left out of the list.  Or it's in the works.

**Comment by MattFiler** [comment]
`reference` is now included in the param list on main :)

**Comment by ghramsey** [comment]
I'll add this here b/c it's related to this enhancement request I think.
Better filtering the dropdown lists would be good.  I suspect this is on your roadmap.

I was looking for something to have my new hostile NPC say.  
I added a speech and randomly chose this line [A1_CV1_G_WAR_C] {I'd turn back if I were you. } 
from the speechscript file.  

The sound event listbox doesn't find it (it does not actually exist as an audio asset). 
I did not realize this at first nor does the dropdown list box for sound events indicate that it's not a valid file.
How about a simple indicator such as a color change? Anything to alert that it's a null entry.

**Comment by ghramsey** [comment]
Unless told otherwise that it's a bug I'll add this here since it's regrding a drop down list.

This is from DLC challengemap13\wave3_  which I was using as a template to make a character banging the window 
as a sub objective:
![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/a64cf192-454e-49ca-9820-f6ace7c58a5d)

When trying to duplicate the settings TriggerSquence has two parameters: Job and filter which are missing from the list.   
Assuming these are not list only I'll manually add them but just FYI.

**Comment by MattFiler** [comment]
Closing this issue and moving the remaining types to #286 to make it easier to track 👍
