### ISSUE TITLE
enhancement: group speech script lines together by event number

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#159]
![image](https://user-images.githubusercontent.com/51859157/223627049-2c44cf60-dd1f-4961-b116-4d05fc7b4218.png)

These speechscripts are shown out of order making it very hard to decipher which character says which line w/o constantly
referring to the script text file. 

Is it possible to group line_01_event, line_01_character, line_01_delay(if present), etc., together so it makes it more logical to read?
If creating a new speechscript it actually these in the correct order.

The only issue is that in some cases the character speaking is not referenced within the speechscript, but still has a line.
So this would need to be compensated for as leaving the character parameter blank or not created for that event.

In any case this is more of a quality of life enhancement that I hope is not too too complex to add.

**Comment by ghramsey** [comment]
As a possible alternative to grouping. Maybe a 'move up' and 'move down' setting for them so they can be re-ordered.
not sure which is easier to implement.

**Comment by MattFiler** [comment]
I'd really like to change the entity view to be node-based eventually so that it's easier to visualise their connections - but yeah something like this would be a nice stop-gap.

**Comment by MattFiler** [comment]
I've solved this by sorting parameters alphabetically - will push up to staging when I have some more changes to go with it 👍

**Comment by ghramsey** [comment]
Impressive! Thank you!

**Comment by MattFiler** [comment]
I've just pushed this out to staging - let me know if you encounter any issues!

**Comment by ghramsey** [comment]
Not sure it's an "issue", but the speech and speechscript windows have a short pause.  
Barely noticible on myI7-9700F, but it's there.  
To me I don't find it an issue though . It is functional and readable.
Thank you for doing this extra work.

**Comment by ghramsey** [comment]
I might have found a minor bug.  I'm not sure if it's from #158  or sorting but when I edited a speech script event in BSP_Torrens and happened to click on the center window it refreshed the edit I just made to the previous version.
This happened even if I saved the file.     I'm going to duplicate this message on the #158 since I'm unsure which is actually at fault.
