### ISSUE TITLE
enhancement: name and syntax checks

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#160]
I'm sure this is on the roadmap and it probably follows hand in glove with better pre-fills, but it would be very nice for an 
indicator that the entry is valid or not. So for CAGEAnimation there is 'playspeed' for CMD Animation it's 'PlaySpeed'.
Those two automatically prefill. Many others do not and will allow incorrect data type or parameter.  
Underscore vs words placed together with a capital letter for each and capital vs lower case letter check would be helpful.

However, I recently found that on the speech and speechscript functions the event is 'sound_event' not 'sound_bank' which
I mistakenly typed (data type 'sound_event' is not present in the list) and only through compare did I locate where I'd gone wrong.  

Also, while copy/pasting I accidentally added a leading space for one of the event names which is a string.  
I almost didn't notice it until I manually typed the name and found the space.

**Comment by MattFiler** [comment]
I've extended support for all parameters in the parameter selection window, so I'm going to close this issue, as it acts as the auto complete functionality you're after here.
