### ISSUE TITLE
"Edit Cathode Scripts" stopped working after closing the "Star in GitHub" window

### ISSUE THREAD

**Issue by Const1702** [MattFiler/OpenCAGE#161]
I tried to open the Commands editor and it told me to star this project in GitHub. I closed the window and went to github.com to do it manually, because I didn't realise I had to click something on the window (I think this is what I had to do). "Edit Cathode Scripts" doesn't do anything anymore even tho I just starred it. Was it the wrong way of doing it? Do I have to wait? Do I have to reinstall OpenCAGE?

Every other tool works.

**OpenCAGE version: 0.9.3.61 (Staging)** (Right after the update)

**Comment by MattFiler** [comment]
Ooh perhaps I've broken something in the new update. One sec!

**Comment by MattFiler** [comment]
Hmm, I can't seem to replicate on my machine. Please could you try delete `DATA/MODTOOLS/` and relaunch OpenCAGE?

**Comment by Const1702** [comment]
It fixed it! It didn't even ask me to star it anymore, it just opened like it is supposed to

**Comment by MattFiler** [comment]
Nice!

I might add a "reset" button in OpenCAGE's settings in a future update which performs that process automatically for you get out of any corrupted downloads 👍

**Comment by MattFiler** [comment]
I've just pushed this out - in the settings menu you'll now find a button called "Verify OpenCAGE Tools" which will automatically perform this for you.
