### ISSUE TITLE
Search For Composite and Tabs for Importing Exporting Composite 

### ISSUE THREAD

**Issue by SneakyEvil0** [MattFiler/OpenCAGE#162]
It would be great to a have a search engine for searching certain pattern or terms or in which Cathode if had been used in the whole Cathode without needing to search for it in every composite of Command.PAK and being to being possible to import or export certain Cathode like in Exemple the Cathode for the NPC for exemple to add it in another Command.pak that does not include it,

**Comment by MattFiler** [comment]
Closing this as I believe it's now covered by #267
