### ISSUE TITLE
Drop down list box spontaneously edits parameter with item from list

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#167]
I happened to click the drop down box for the parameter on this entity.  
The default entry is 'enable'.  Upon closing the dropdown the box spontaneously became enable_on_reset.  
It should be 'enable' which does not appear in the list. If I didn't see what the entry name was I might not have 
noticed this had occured. 
 
I took a screen shot of before and after which I hope better illustrates the issue.

I'm not sure how wide spread this issue is.  But I suspect the reason in this case is that 'enable' is not on the list so it's 
auto completing the entry.   

Hopefully this is not a side effect of any of the recent changes.

This might not actually be a problem unless I hit save.  But if I failed to realize I'd made the change it could be problematic.

![image](https://user-images.githubusercontent.com/51859157/225024810-fee58b87-202a-4b0b-bcff-bad724e3564d.png)
![image](https://user-images.githubusercontent.com/51859157/225020986-18ea07d4-d4f8-40ed-82d2-43e87660105f.png)
![image](https://user-images.githubusercontent.com/51859157/225021014-47dc98de-b3ec-4de8-b3d2-195c4e75a3f6.png)

**Comment by MattFiler** [comment]
This should now be fixed on staging for asset and parameter selection.
