### ISSUE TITLE
bug: TerminalContent dropdown listbox populated with OBJECTIVE strings

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#169]
I am making this as a bug ticket in case you missed my mention on the enhancement #158.

![image](https://user-images.githubusercontent.com/51859157/226130362-528e065e-05ae-4e22-8f8e-cfd5e9ccdb46.png)
The speechscript dropdown list in some cases is showing only OBJ files. 

It might be related to the this bug #167

**Comment by MattFiler** [comment]
This should now be fixed.
