### ISSUE TITLE
OpenCage incorrectly shows 'staging' when on main branch

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#170]
![Untitled](https://user-images.githubusercontent.com/51859157/226686610-e4ad4846-dbf9-463e-b4a9-d66c1dd0fa93.jpg)

I unchecked the options for staging branch.   Since that bug with terminalcontent is only on staging.
It goes through the motions to download the update for main branch. 
It updates the version number, but continues to show 'staging' instead of 'main'.

**Comment by MattFiler** [comment]
This is a known issue & due to changes with how the staging branch is implemented within the staging client. Will be resolved once the update goes down to main :)

**Comment by MattFiler** [comment]
I'm closing this to clear out the issues list a bit as it's something that'll be automatically resolved next release.
