### ISSUE TITLE
Suggestion only: "References" window for composite instance locations

### ISSUE THREAD

**Issue by Const1702** [MattFiler/OpenCAGE#186]
In the "Composites" sidebar there are two buttons: "Add Composite" and "Remove Selected". Another one would be useful for finding out where a composite is instanced (doors, keypads, etc...). When a composite is selected the button will be available, but if a directory is selected like this (not a composite inside of it)...:
![image](https://user-images.githubusercontent.com/116276106/233802281-619e548b-aaea-492d-a271-73d76ac4a4af.png)
...the references button for the composite will obviously be greyed out (because a directory is not a composite). A lot of times I see a composite in the game whose location I don't know. Going to the actual composite in the sidebar (and not look through the lists to see where it is instanced), then opening the references window and it showing me all the locations where it is added to and just clicking "Jump to" would take me there, would be nice. I hope a feature like this is even possible.

_Also congratulations on importing the first custom model in the game with the asset editor! Hope it progresses well!_

**Comment by MattFiler** [comment]
This is a great suggestion & actually something I've been wanting too after using the tools a bit more myself recently - thanks!

More info on the model import/export very very soon!

**Comment by MattFiler** [comment]
Will push this to staging shortly!
