### ISSUE TITLE
Cloning doesn't work on some NPCs

### ISSUE THREAD

**Issue by Cervicia** [MattFiler/OpenCAGE#194]
When cloning some NPCs for example humans, they won't spawn. The only thing, that is visible is the model of their weapon. Steps, I did: 
- searching in the _missionscript_ for _human_
- cloning one of the entities(composite) and setting a new position
<img width="952" alt="AI_NPC_weapon" src="https://user-images.githubusercontent.com/100235168/236539854-284d1523-b0dd-4423-95b4-6e4624f0b60d.PNG">
Moving the position of exisiting humans works fine.

**Comment by MattFiler** [comment]
Done a bit of digging into this, it appears that NPCs compile to a separate binary file called CharacterAccessorySets which defines the bodyparts to spawn for NPCs (hence why you're only seeing guns). Will see if I can add support for it to the script editor!

**Comment by MattFiler** [comment]
Update: there was an unknown value in the NPC setup file which I've now figured, out making this possible! Will add support for it in the next update, along with some improved MVR stuff as a result of the new finds, which should help fix #95 too.

**Comment by MattFiler** [comment]
![20230529225318_1](https://github.com/MattFiler/OpenCAGE/assets/6270995/cacf9f95-69a5-43ea-b00b-1ae4a11c3daf)

Pic of the first custom human NPC spawned in using the NPC editor! Will push it out to the staging branch soon after some more work.

**Comment by MattFiler** [comment]
This is now live on staging!

When you create a custom NPC, follow the composites through until you reach the `Character` entity within. Select the `Character` entity and then press the "Function" button. In the window that appears, press "Add New" and select your NPC in the dropdown list (this list is a hierarchical view of all spawned NPCs that point to this `Character` entity, so look for the name you gave it within the hierarchy), then click add.

With the instance of your new NPC added to this editor, you can then begin setting up the NPC's attributes. Currently available is support for:
- Adding composite references for the character's head, torso, arms, legs, shoes, and collision.
    - To do any of these, click the "Change" button and select a composite. Ideally look in the NPC directory & select something appropriate. I've left it open to any composite incase you add any custom ones.
- Selecting the skeleton of the NPC.
    - Ideally, keep all components of the NPC the same gender to avoid rigging issues.
- Shirt decals.
    - This is a choice of either medical, engineering, generic, or technical. Some of these choices not only change the decal but also some colour variations on certain clothing. I'm still working on figuring out where this data comes from.

I'll continue to expand the character editor over time as I learn more about the format, and I also plan on adding a previewer to see your character easier in the editor.

Thanks for the request!

**Comment by MattFiler** [comment]
Glad to hear it worked! Will fix that skeleton bug - thanks for spotting 👍
