### ISSUE TITLE
Several windows are maximizable when they shouldn't be

### ISSUE THREAD

**Issue by Const1702** [MattFiler/OpenCAGE#196]
A small issue for some windows that can be maximized when either right clicking on the window box (or pressing Alt-Space) which shows the maximize option as available or when double clicking on the window box which also maximizes it.

**Here are the windows:**
Landing page settings:
![image](https://github.com/MattFiler/OpenCAGE/assets/116276106/41d48190-3515-4157-9aba-05ef9be814fb)
![image](https://github.com/MattFiler/OpenCAGE/assets/116276106/d5d0ac85-d9ca-485d-b729-a5b722836191)

Script editor's spline editor:
![image](https://github.com/MattFiler/OpenCAGE/assets/116276106/f82bec9b-10f9-4fd0-a8b0-ca0e2aaa41ac)

Asset editor models - model editor window:
![image](https://github.com/MattFiler/OpenCAGE/assets/116276106/700aa5c3-eece-45b4-b803-e6c8b0914518)

Asset editor models - model editor's material editor/previewer:
![image](https://github.com/MattFiler/OpenCAGE/assets/116276106/e12188f0-d91b-40ed-96de-fcdd5cd84e39)
 
For now these are the windows I found. Will let you know if I find another.

**OpenCAGE version: 0.10.0.0 (Staging)**

**Comment by MattFiler** [comment]
Thanks for spotting!
