### ISSUE TITLE
enhancement: script editor shows commands.pak files in other subfolders too

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#205]
This is not a bug per se.  More a housekeeping suggestion I guess.

I have backup folders off of each world folder with a commands.pak.  Sometimes more than one.
The commands editor is parsing those folders showing commands.pak files it can't open.
Can it only parse the main commands.pak and not alternate locations ?

![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/dfd7a7fd-e7c7-42c9-a858-263d896f880a)

**Comment by MattFiler** [comment]
Interesting folder structures - the tool will show all COMMANDS.PAK files in the ENV folder, rather than levels. I'll mark this as a bug and change that functionality to just show map folder names.

**Comment by ghramsey** [comment]
OK.  However it works best for work flow.   Thank you for all you do.

**Comment by ghramsey** [comment]
Much cleaner looking now. Thank you.  But seems to have missed one;

![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/c7e09392-98aa-4781-aa1f-47e8cdd2b4c6)

All the extra commands. files except one have been eliminated:

Here's the actual folder:

![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/6e6bbbeb-45cb-4c24-a33d-15e66d8dacc1)

**Comment by MattFiler** [comment]
What's in the "New Folder"? Is it a complete copy of WORLD?

**Comment by ghramsey** [comment]
Yeah. It contained a 1:1 backup of the hab_corporatepent folder including all of the usual file structure.
I think  I must have zipped the folders but didn't remove them afterwards. So They were not supposed to be kept.
I removed all of those unaltered folders leaving only a commands.pak and the list no longer show that extra entry.

**Comment by ghramsey** [comment]
One more thing on this.  
Commands editor no longer "sees" the 'new folder' commands.pak and hierarchy but weirdly in the
debug menu the game does.   

![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/2a058be2-315e-4409-9bc7-b4b2e338ccd8)

It's not an issue, but just an interesting find.   
Additionally, it's the only subfolder that the game shows in the debug menu though I've changed none of those folders.
I wonder what is unique about it ?

**Comment by MattFiler** [comment]
Thanks for highlighting - this stuff is managed by the launch game functionality, which I'll patch with the same logic used in the script editor now.

**Comment by MattFiler** [comment]
The updated level list is now in the launch game tool, and should also reflect correctly in-game.
