### ISSUE TITLE
[questions] bml <> XML command line converter

### ISSUE THREAD

**Issue by john-peterson** [MattFiler/OpenCAGE#207]
I'm just looking to edit the bml files at first

Props for the enormity of this app. I see a great game maker 

Anyway. I just want to do that at the moment. And I usually work in the command line

Just putting this here if anyone else is thinking about this. Maybe in 2033 I will do it get around to it

Typically in a project like this I would like to see at least a few command line options. This is a glorious  desktop experience. Good way to make money :-P

I will try to dig up the code for what I'm talking about and link the repo here to only that single line of code that does what the topic says

**Comment by MattFiler** [comment]
Hey!

The BML code is based upon [AlienBML](https://github.com/x1nixmzeng/AlienBML) which offers command line operations for converting files.

Hope this is useful!
