### ISSUE TITLE
nodegraph viewer objects overlapping cannot be moved

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#208]
The nodegraph bubbles can no longer be moved now that they're linked to the commands editor. 

Clicking on the bubbles refreshes the nodegraph window and refreshes the commands editor. 
Now when they overlap like this they can't be moved.

![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/0a4cd446-6882-4f57-b236-373b645aba3f)

I've noticed before that very large graphs can become messy-looking when many link lines are leading from 
one side of the graph to the other.    Not sure there is much of a fix for that since it's showing a graph of nodelinks.

**Comment by MattFiler** [comment]
you can resize the window which might help the layout for bigger setups - good spot on the drag issue though, will change that behaviour

**Comment by MattFiler** [comment]
I've fixed this in a branch: you can now enable the selection feature via a checkbox, or disable it if you prefer.

Will merge it down to staging shortly, but marking it as done so I don't forget :)
