### ISSUE TITLE
Backups should back up the whole level, not just COMMANDS.PAK

### ISSUE THREAD

**Issue by MattFiler** [MattFiler/OpenCAGE#209]
Within the scripting tool, the auto-backup feature should backup the entire level, rather than just COMMANDS.PAK now that the scripting tool touches more files than just that.

Would also be good to have a backup browser to be able to restore older level backups with timestamps.

**Comment by ghramsey** [comment]
I whole heartedly agree on the backup list and time stamps.  

This would go worlds toward the hearty list of backups (and that weird folder heirchy I've created) being unneeded.
Since the files are all commands.pak it's hard to keep track of them.

**Comment by MattFiler** [comment]
I've added a first-pass of this to staging!
