### ISSUE TITLE
Small typo in the Alien Configuration Editor

### ISSUE THREAD

**Issue by MrKoroshiya** [MattFiler/OpenCAGE#21]
Hello!
In the Alien Configuration Editor, as part of the OpenCAGE software, the word "gauge" is incorrectly spelled multiple times as "guage".

That's all, thank you for your work!
![guage](https://user-images.githubusercontent.com/42919840/82122842-44009980-9796-11ea-80ed-4430590504bf.png)

**Comment by MattFiler** [comment]
Cheers! Fixed as of #22
