### ISSUE TITLE
Suggestion only: When choosing a composite to create, a window showing the composite sidebar should open, instead of a dropdown

### ISSUE THREAD

**Issue by Const1702** [MattFiler/OpenCAGE#217]
When creating composites with the "New Entity" window, you need to select the one you need and this is a bit difficult, because it is just a dropdown menu showing all  the composites, which are a lot most of the time. This makes the scrollbar sensitive and hard to move to the entity you want. A good replacement would be a window showing the composite sidebar that can always be seen on the main window. It will probably look something like this:
![image](https://github.com/MattFiler/OpenCAGE/assets/116276106/2aefccf6-01a0-4a9b-854d-430b1bb07bbc)
_Reference photo from the NPC editor_

**Comment by MattFiler** [comment]
I completely agree, will defo be in the next update! The dropdown is annoying 😆

**Comment by MattFiler** [comment]
This is now live on staging 👍
