### ISSUE TITLE
Materials editor export "part0" in component list hierarchy show only file extention

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#221]
I'm trying my hand at exporting a model again.  With backups of the models file this time should I break something again.
I found this issue before but I didn't think to report it until now.
![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/91d958b2-a64f-4a34-b6c0-109db7b1d9e1)
![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/5b8fe339-2845-4088-aa5f-d7f7cf55e0b9)

When selecting each of these part0 is the only one that shows no file name automatically when exported.  
I hope this description and screenshots make sense. 

A name must be supplied or it will export with only the file extension.  I suspect this is level should not be exportable.
I think from experience that the top level of the part export data is same as that first level "part0".   

This issue only happens on the level called "part0" on each component though. part1, 2 etc do not exhibit this issue.

I know you have a rework of this editor in the pipe so this might be a superfluous bug report.

**Comment by MattFiler** [comment]
I've fixed this in a branch that I'll merge to the staging branch soon, but will mark this as completed anyways so I don't forget 😅
