### ISSUE TITLE
Mover descriptor editor : rotation and scale data change spontaneously

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#222]
I made a short clip: https://www.youtube.com/embed/oEb2HSvwXUQ

I'd edited a door keypad mechamism including it's mover settings. Many of them.
I ended up with a collision barrier that was not going away when the door was opened.
So I decided to just undo the changes.  I changed it back using a copy of the vanilla game in epic store as template. 
Loaded into a normal game and found the door mechanism was 90 degrees off.    Checking the settings, I found 
the position x,y,z coordinates were correct, but the rotation and scale information was changed.   (Of note here too 
is that I did not edit the rotation nor scale information when making the initial change. I edited only the Z position
to 0 in attempt to remove the mechanism off the map.)

When I change them the rotation and scale information they spontaneously changed to different information.
The rotation seems to move "left"; W>Z, Z>Y, Y>X and X>W when I select another mover in the list. 
I did use Type = 3 when making the edits as the instructions indicate. This worked to edit the mechanism, but not when reverting.

**Comment by MattFiler** [comment]
I've slightly improved this, will merge it to staging shortly. It's still not perfect though, the precision of the data conversions is a bit off 🤔

**Comment by MattFiler** [comment]
Fixed this, and also changed it to be euler rather than quaternion so it's the same as the data in the position parameter. Will merge to staging shortly!
