### ISSUE TITLE
New composite with trailing '\' makes blank named composite

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#229]
![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/741d7e58-fc0b-4f85-93a5-6a115a4d8ff9)

I added a new composite as 'AYZ\CONTROLS\TINYBUTTON\'  
I inadvertently typed that extra backslash and the heirchy produced TINYBUTTON > _ 

It did what it was told I guess. But surely that is not intended to allow blank names?

I can select and remove it to recreate, but I figured this might be something you want to 
address while you have been working on the commands editor.

**Comment by MattFiler** [comment]
I've implemented this now & will merge it to staging next time I do an update there 👍
