### ISSUE TITLE
Unable to rename existing entites

### ISSUE THREAD

**Issue by Const1702** [MattFiler/OpenCAGE#246]
On any level, on any entity type, the rename button is nowhere to be found. At least I don't see it. The only way to rename an entity is to delete it and re-create it with a different name. Was it moved?

Apologize for not reporting earlier! Just didn't notice this before.

**OpenCAGE version: 0.10.2.25 (Staging)**

**Comment by MattFiler** [comment]
Not re-added yet. Thanks for flagging!
