### ISSUE TITLE
Entity ID field missing only in Epic Games Store version of editor

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#254]
![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/3c211fdf-7184-45f8-a99d-ad63b833debd)
Something I noticed when opening EGS and Steam versions side by side: the ID field is missing on EGS version.

Maybe something unique to EGS?  I've been using the commands paks interchangeably w/o issue, but this stood out.
It doesn't seem to be causing any problems.  Just visual?
I think this has been like this on versions of the new UI since the ID field was added.

**Comment by ghramsey** [comment]
Nevermind. I see there's an option in the dropdown list.  For some reason it's toggled off on the EGS editor.  
Disregard this .  I'll close it.

**Comment by MattFiler** [comment]
Yeah this is off by default now! Turning it on will update all the hierarchy strings and stuff too. Figured some people probably wouldn't want it on as it looks messier, so it's off by default.
