### ISSUE TITLE
Move pre-filled asset dropdown suggestions to separate UI.

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#255]
I found myself on a speech entity and scrolling the mouse wheel on the wrong window which changed the speech event.

I could not figure which was the right one.  Had to revert to a prior save.  Not a big worry but it's very easy to mistakenly 
change list boxes when scrolling mouse wheel.  Is it possible to make the changes 'stick' only with a confirm change button?

Anything to prevent accidentally changing the information within the list without knowing what the previous or default value was.

**Comment by MattFiler** [comment]
I've been debating for a while having an external window to select the pre-filled options, so I guess that would resolve this problem. My intention with the external windows was to improve the load speed for `Speech` entities and others that auto populate a load of options.

**Comment by ghramsey** [comment]
Sounds great!

**Comment by Const1702** [comment]
This could probably be also added to the "Edit Entity Pin Link" window when you are selecting an entity, as in a lot of composites there is a large amount of entities, so the scrollbar is sensitive and hard to get to the entity you want. The way I do it is to get the entity ID from the main list by searching for it, then open the link window and type in the first letters and numbers (ex: _[86-FC_), after that I just press arrow up/down and it auto-fills it, but now that IDs are disabled by default, most people would have to use the scrollbar to get to the entity they want. Here is a case where there are a lot of items in the dropdown list:
![image](https://github.com/MattFiler/OpenCAGE/assets/116276106/6b80b40a-8e5a-4908-aed8-cb1b4113e6b9)
I know that they are sorted in alphabetical order, but a window showing all entities with a search box (maybe similar to the "Edit Hierarchy" one, just without the "Follow entity through" button and a different title like "Select Linked Entity"), would be nice. This is kind of similar to the closed issue: #217.

**Comment by MattFiler** [comment]
Ah yes I've been meaning to improve that UI for a while and keep forgetting, thanks for raising. I've converted it into a separate issue.
