### ISSUE TITLE
References to re-named entities do not update until file is reloaded

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#256]
This might be by design, but in case it's not...
I noticed that entities that I've renamed work OK and update immediately, 
but references retain the prior name until I save and reload the file.
I don't remember if it was this was in the old UI.

**Comment by MattFiler** [comment]
Ah yes, I reload the current composite entities but forgot ofc that ones that point across composites will also need updating. Thanks for spotting!
