### ISSUE TITLE
When many tabs are open moving UI window repositioning is slowed

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#257]
I noticed that the UI window seemed to "float" instead of moving smoothly and it seems to be happening and worsens when
many tabs are open.  Some sort of memory or perhaps graphics memory use thing?

Here's a googledrive link to a video clip:
https://drive.google.com/file/d/1jXQMQY56-Nri6jPHhKbmdBCUf14Soren/view?usp=sharing

**Comment by MattFiler** [comment]
I've tried recreating this locally with 20+ composites and 10+ entities open in each and it still appears to be running just fine. Out of interest, what are your PC specs?

Opening a lot of entities and composites on a slow system is likely to be laggy on older hardware. You have to remember the previous script editor only allowed one composite and one entity to be open at once, and was way less GPU/CPU intensive without the docking.

I've got #245 open to add a context menu to quickly close composites and entities which should hopefully make it easier to close things you're not using, which will improve performance on lower end hardware.

**Comment by MattFiler** [comment]
Also - going to close this as like I say above it is just kinda expected to be slow with a lot of things open on lower end hardware.

**Comment by ghramsey** [comment]
Maybe it's local. IDK.  I have an I7-9700F, 16GB RAM, and an RTX3060 with 12GB video ram on a Gigabyte desktop board.

I keep the video drivers up to date too b/c nvidia pushes them like every month.  I have two monitors with desktop seemless mode.  One on DP to DVI into the monitor the other on straight HDMI.   I don't normally see any video issues.   I run games 
like Hitman 3 on max specs without a stutter.  

But I can see how the tabs would slow things which is why I reported it.   If someone with say a laptop had that happen 
it would might be more eventful but if you can't reproduce it then it's something unique to my own setup.

I don't like making tickets that amount to nothing.  It feels like I make enough extra work as it is.

**Comment by MattFiler** [comment]
Huh those specs are better than I was expecting given the ticket 😅

I'll re-open and look to see if there's anything I can do, but since I can't replicate locally I'm not so sure.

**Comment by ghramsey** [comment]
I should have put my PC specs in that ticket too.   Also, Windows 10. Not 11.  And a quad of NvME M.2 SSDs.   
Two on the board and two reside on an add-in PCIe card that has bifurcation chipset to share the buss bandwidth properly.

It's not really an issue for me.  If you can't reproduce it and nobody else flags this as an issue for them then no foul. 
I figured it as an FYI as much as anything since lower specs as you indicated could very well experience problems.
Being able to close tabs via menu will probably help in any case.

**Comment by ghramsey** [comment]
I was doing some checking on this.  It seems that many composite tabs do not cause any problems; 
it's when I open a composite and click a bunch of entities within that I notice the window is slow if I move it around.  

I also noticed that the monitor I usually use it on use a DP >DVI conversion and seems to exhibit more slowing when I move 
the window to the HDMI side it is less noticible.  Maybe this is unique to my setup after all, but I suspect that the sub-menu 
you've planned to close tabs will certainly help.

**Comment by MattFiler** [comment]
I've implemented the tabs now and haven't found a way to replicate this, so I'm going to close it.
