### ISSUE TITLE
enhancement: protect essential composites from accidental use of "delete composite"

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#260]
The other night I clicked 'delete composite' and hit enter immediately so the pop-up warning didn't help.   
I meant to click delete checked entities.    It was simple to revert to previous save and nothing bad happened.   
At this point though I could accidentally delete root and the program would do that without question and that 
seems a bit over powered and certainly not intended.

I was thinking maybe a protection on critical composites root, ambient and story mission (at least) should be made too?

Alternatively and in the meantime, can the 'delete composite' button be moved a little more separate from the rest and perhaps 
red color?  This will make it less likely to be used accidentally.   Maybe too a 1 second delay in being allowed to hit enter on the OK button?  That would also prevent clicking and using enter immediately.   Even a teeny delay would have prevented my essentially ignoring the warning pop-up.   Might even be enough on it's own.

**Comment by MattFiler** [comment]
The root composite does already have protection on it against deleting.

To try and solve this issue, I've moved the buttons around in the new UI. "Delete Selected Entities" is now next to the "Create Entity" dropdown, and has an appropriate icon.
