### ISSUE TITLE
"Verify files" deletes 'data/modtools/backups file structure'

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#270]
Had to use verify files from the gear icon.  

Opened backup manager later and found everything is no longer there.
All folder structure of the data/modtools/backups are deleted during the verify.

**Comment by MattFiler** [comment]
Oof, this is a good spot! Apologies!!

**Comment by ghramsey** [comment]
Its OK.  I'm glad I've not made any changes that I had to undo though.

**Comment by ghramsey** [comment]
Cool!
