### ISSUE TITLE
Improve entity selection in pin editor

### ISSUE THREAD

**Issue by MattFiler** [MattFiler/OpenCAGE#274]
> This could probably be also added to the "Edit Entity Pin Link" window when you are selecting an entity, as in a lot of composites there is a large amount of entities, so the scrollbar is sensitive and hard to get to the entity you want. The way I do it is to get the entity ID from the main list by searching for it, then open the link window and type in the first letters and numbers (ex: _[86-FC_), after that I just press arrow up/down and it auto-fills it, but now that IDs are disabled by default, most people would have to use the scrollbar to get to the entity they want. Here is a case where there are a lot of items in the dropdown list:
![image](https://github.com/MattFiler/OpenCAGE/assets/116276106/6b80b40a-8e5a-4908-aed8-cb1b4113e6b9)
I know that they are sorted in alphabetical order, but a window showing all entities with a search box (maybe similar to the "Edit Hierarchy" one, just without the "Follow entity through" button and a different title like "Select Linked Entity"), would be nice. This is kind of similar to the closed issue: #217.

_Originally posted by @Const1702 in https://github.com/MattFiler/OpenCAGE/issues/255#issuecomment-1711491493_

**Comment by Const1702** [comment]
It is looking good, but I noticed that it doesn't show aliases (overrides) in the pop-up window. Only in the old dropdown box.

**Comment by MattFiler** [comment]
Good spot
