### ISSUE TITLE
Objective list / tooltip does not update correctly

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#282]
![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/b1070354-df09-44f6-8d4d-06b638284528)
![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/c28c383a-38d9-4071-be9d-86e2b03d1794)

I inserted a custom objective into the correct file (Ojectives not the mission script) this time and it works in game. 
I changed "Find a Trauma Kit" event 300 to be "Exit The Morgue" and added an event 0301.

Just a minor nitpick though. The custom objective event A1_OBJ_M10_0301 does not show in the drop 
downlist which might be by design IDK (are you reading the objectives .txt file?), but even when I change it 
manually the tooltip is showing the text of the last event that I was on that is in the list.  Since the event is not 
in the list in this case the tooltip should remain blank or if the list is supposed to be updated from the objectives 
file then it should show the tip based on the text there in.

**Comment by ghramsey** [comment]
Oh I did reload the command editor and reload the map after editing the file but it seems like it didn't update still.

**Comment by ghramsey** [comment]
Well... After closing the commands editor  a 2nd time and reloading the list did update.  
I don't like making unnecesary tickets.   I think this is a disregard.  It seems to be OK after all.

**Comment by MattFiler** [comment]
Another tip as well - if you don't care about localisation, you can always just type the new string right into the script editor and not worry about the whole ID system.

**Comment by ghramsey** [comment]
After the debacle with that text and the blank space becoming corrupted characters, I've been leary to directly type into the fields.  
I didn't actually type that either it was something in the stock game I think actually(?). 
But if it'll work and not break something again I'll consider doing that.

**Comment by MattFiler** [comment]
Yeah that one was with a string from the base game. You'll find they don't tend to use the localisation system in places where they were testing things out, or prototyping things.
