### ISSUE TITLE
Commands Editor: "not responding" following toggle of show EntityID option to on

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#283]
Torrens map has three functions named logicdelay_2 so I wanted to see which was which. Turned this feature on and this happened.

Changing the Entity ID setting from the menu to "on", in this case results in complete hang and a not responding window.
I'm not sure if it will recover or if it's completely stuck. I  will give it a few minutes but I'm almost certain this is probably 
gonna need a manual exit from the task manager.

It happened 1st time I thought it was isolated and killed task tried again.  Same thing.

**Comment by MattFiler** [comment]
Good spot - if you wanna enable/disable it for now, close all composite tabs first. Should work.

**Comment by ghramsey** [comment]
Yes. I just figured that out. Toggling it when no map file is open works around the issue too.

**Comment by MattFiler** [comment]
Should now be fixed on latest staging.
