### ISSUE TITLE
Suggestion only: Add duplicate option to entity list context menu

### ISSUE THREAD

**Issue by Const1702** [MattFiler/OpenCAGE#289]
In the parameter view you can rename/delete/duplicate:
![image](https://github.com/MattFiler/OpenCAGE/assets/116276106/a48c1c23-9349-41bc-877a-126ea6d208bd)

In the context menu you can only delete and rename:
![image](https://github.com/MattFiler/OpenCAGE/assets/116276106/50ade3ee-7af8-4fad-bce3-68298f97e061)

For more consistency the duplicate button could also appear in the context menu.

**Comment by MattFiler** [comment]
Will push this to staging in the next update :)
