### ISSUE TITLE
LOD Issue 2

### ISSUE THREAD

**Issue by d0x360** [MattFiler/OpenCAGE#31]
In response to you I did also set it to 1 and I also tried bumping it up to 2,3 and 6 but I was still seeing pop in and LOD changes.

Is there any way to make them go away 100%?
My PC can handle it.

**Comment by MattFiler** [comment]
Please refer to issue #30 rather than creating a new one - as I say, the LOD value is a scalar, so if you want to remove the effect of LOD set it to something large: my example was 10,000. At values like 6 you'll still see the pop-in.
