### ISSUE TITLE
Debug Checkpoints won't be avaliable until a save is created in the current level.

### ISSUE THREAD

**Issue by ProjectHSI** [MattFiler/OpenCAGE#310]
When launching the game using the Launch Game tool, the Load Game option, and thus, the Trigger Debug Checkpoint option won't be available. This requires getting to a save point, saving, and then triggering a debug checkpoint.

**Comment by MattFiler** [comment]
Gonna close this issue as it's just the design of the game - similar to how debug checkpoints aren't available in DLC maps.

**Comment by ProjectHSI** [comment]
closing as not completing (if possible) as i feel as that's better for this issue.
