### ISSUE TITLE
Support running OpenCAGE from outside the AI directory

### ISSUE THREAD

**Issue by ProjectHSI** [MattFiler/OpenCAGE#311]
If any of the mod tools are open at all (even the OpenCAGE main executable), the Epic Games Launcher will detect the game as "Running", and will not allow Alien: Isolation to run if launched through the Launch Game tool.

**FIX** (kind of, and at least for me): Move the OpenCAGE executable and configuration file into a different directory (prevents the OpenCAGE launcher from trigger Epic Games' game detector), then create a symlink from the different directory's configuration file into the Alien: Isolation root folder (allows the tools to work).

**Comment by MattFiler** [comment]
I'll leave this open as a ticket to bring back the ability to run OpenCAGE from anywhere on your system, as it'd present an easier solution to the Epic fix.

It's annoying that Epic don't register the exe of the game like Steam do, as it results in this dumb system where the first exe run in the game's directory is counted as the game process running 🫠

**Comment by ProjectHSI** [comment]
> I'll leave this open as a ticket to bring back the ability to run OpenCAGE from anywhere on your system, as it'd present an easier solution to the Epic fix.
> 
> It's annoying that Epic don't register the exe of the game like Steam do, as it results in this dumb system where the first exe run in the game's directory is counted as the game process running 🫠

I should note though that I have been able to get the OpenCAGE launcher running outside of the A:I directory. although it requires using the command line. This workaround is described in the fix in the initial issue description.

**Comment by MattFiler** [comment]
This is now supported on the staging branch (grab the OpenCAGE exe [here](https://github.com/MattFiler/OpenCAGE/raw/refs/heads/staging/OpenCAGE.exe)) - if you launch OpenCAGE outside the AI folder it'll ask you to locate it :)

**Comment by MattFiler** [comment]
Actually, I've just gone ahead and pushed this to main as fixing the Epic issue seems pretty important. Thanks for flagging!
