### ISSUE TITLE
Search bar does not clear after editing;  add a 'clear search'

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#314]
Whenever an entity has been edited the windows refresh.   If there was a search the list is reset too, but the search bar
remains with whatever was last searched for.  The search button under this condition does not work for that search and 
only searching a blank string  or for something else clears the search.  Can we have a "clear search" button?

**Comment by MattFiler** [comment]
Added this button (it'll show up when a search filter is active), and I've also reworked the searching logic so that if you go through to another composite while you have a search filter active, it'll apply there too.
