### ISSUE TITLE
Cinematic Tools may fail to inject if multiple "AI" processes exist

### ISSUE THREAD

**Issue by ProjectHSI** [MattFiler/OpenCAGE#323]
OpenCAGE fails to load Cinematic Tools due to an issue in Injector. If [this issue in Injector](https://github.com/nefarius/Injector/issues/28) is resolved this can be closed.

This is with Injector and not Cinematic Tools as System Informer is able to inject Cinematic Tools into the game, while OpenCAGE and Injector cannot.

If you wish to reimplement System Informer's functionality, the relevant C code can be found at https://github.com/winsiderss/systeminformer/blob/17c58464ae2719fa0315d82fd4dabec6e2db0c8c/phlib/native.c#L2274C19-L2274C19

**Comment by ProjectHSI** [comment]
Not related to this issue but I can't seem to find a way to use the mouse when injecting the DLL with System Informer.

**Comment by MattFiler** [comment]
Thanks for flagging and pointing to the ticket. Will keep an eye on it :)

**Comment by ProjectHSI** [comment]
As mentioned in the recently edited issue, the injection function isn't tied to System Informer as whole. PHLib (capitalized in my best interpretation) is able to be compiled without build System Informer itself.

This means that PHLib could just be imported into the LaunchGame tool. Since these tools are tied to Windows, needing PHLib probably doesn't matter.

**Comment by ProjectHSI** [comment]
> A note on your comment in the other ticket "probably as I'm running x64 Windows" - AI is a 32-bit game, so would be expecting to use the 32-bit injector there.

x64 Injector actually gets further than x86.

**Comment by ProjectHSI** [comment]
Hey, just curious; does `Enable Cinematic Tools` work on your machine, and if it does, what architecture is your system on?

**Comment by MattFiler** [comment]
Yeah works fine for me & have never had any reports of issues which is odd. Have you tried asking others on the Discord to see if they've had any success? I'm wondering if perhaps your antivirus is blocking the inject action.

I'm on a 64-bit system, but the AI application is 32-bit.

**Comment by MattFiler** [comment]
Oh also another point to raise to this ticket - are you using the injector in the cinematic tools folder, or are you using the "Enable Cinematic Tools" option inside OpenCAGE? They're different things. I assumed you were using the former when you originally opened the ticket as you linked the issue in the Injector project - but your most recent reply seems you may be using the latter?

**Comment by ProjectHSI** [comment]
I used the Enable Cinematic Tools option first. I investigated further and found that Injector threw the error. I've since been using System Informer to inject the DLL into Alien: Isolation manually.

I oddly don't remember finding the Injector in the cinematictools folder. Don't think it would've mattered either way.

**Comment by ProjectHSI** [comment]
An update was made; this issue was mainly because there was a process named "ai.exe" running for a piece of software i use. This was interfering with Injector and causing the process to be injected into ai.exe and not AI.exe.

I recommend that OpenCAGE calls Injector with the Process ID flag, or when PR #30 in Injector is merged use the -c flag.

**Comment by MattFiler** [comment]
Hey, as mentioned, OpenCAGE doesn't use Injector - but thanks for updating the issue :)

It already looks for processes named "AI" - but I'll see if there's some additional filtering I can do there if there are multiple matches.

**Comment by MattFiler** [comment]
Pushed a fix for this out to the staging branch in 0.12.0.02. Please let me know if it has resolved the issue!

**Comment by ProjectHSI** [comment]
I recommend you to merge https://github.com/OpenCAGE/CinematicTools/pull/1 and https://github.com/OpenCAGE/LaunchGame/pull/2. The first PR deletes files that use or were Nefarius' Injector, the second one uses the exe file path to sift instead of the window title. Haven't checked the second one but I think this works if I'm reading the documentation right.

**Comment by ProjectHSI** [comment]
This happened again - staging branch, same thing. Killing the ai.exe (from Outlook) worked to fix.

I did this after a while of not using the Cinematic Tools, if LaunchGame is supposed to download cine tools or something, then this doesn't need reopening, otherwise, this needs further investigation.
