### ISSUE TITLE
Searching for entities from Edit Entity Pin Link not behaving as intended

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#328]
I made a short video clip on this.  When searching for an entity in the list has changed recently.
 
 I was creating a speechscript from a speech and needed to copy those links one by one.
 When I paste them into the search bar as the video shows the search fails.   I do not think this is as intended.
 And doing this used to work.  I'm not sure when it changed.
 
 Also, at the end of the clip.  When I pasted the  link into the box, it kept popping up a message that I had not completed all
  the fields.  This has actually not happened before, but is a side effect of this issue.  Because the entity can't be searched 
  for it the field  would  not complete to the program's satisfaction.

https://github.com/MattFiler/OpenCAGE/assets/51859157/b14ce83a-41b1-4a43-b4fd-91ec713188b0

**Comment by MattFiler** [comment]
I've changed this UI in the latest staging update to better reflect the new entity list
