### ISSUE TITLE
OpenCage does not work.

### ISSUE THREAD

**Issue by SemRevitto** [MattFiler/OpenCAGE#33]
Using this program, I found that nothing in the game changes. After changing the parameters in the Vision Editor, the alien continues to kill me, although I set all the parameters to 0. In The character Attribute Editor tab, I changed the parameters of its health, but nothing changed in the game. I also tried to run the game as an administrator, but nothing helped. How to fix this problem, please help me?

**Comment by MattFiler** [comment]
Hey, unless you can provide some specific examples of issues with the toolkit I'm going to close this issue.
Please check out the wiki for more information on parameters to edit 👍
