### ISSUE TITLE
unhandled exception causes silent crash while scrolling through entity list 

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#330]
I got a silent crash while scrolling through the entity list. I have multiple tabs view open, but I close
the lot when it seems like it's chugging to draw them.

I feel like this is related some how to #319 because the symptoms are similar.  Doing something "too fast".
I'm scrolling through the list of entities and it's still drawing/populating the list as I get to the next item
and there seems like a blink and then CTD.  No error from opencage.

This is staging ver. .35

Windows Event viewer shows this as the reason for the crash:

[-](https://github.com/MattFiler/OpenCAGE/issues/new#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/MattFiler/OpenCAGE/issues/new#) <System>

  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-02-08T15:21:47.2842538Z" /> 
  <EventRecordID>217238</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>ghram</Computer> 
  <Security /> 
  </System>
[-](https://github.com/MattFiler/OpenCAGE/issues/new#) <EventData>
  <Data>Application: CommandsEditor.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.ComponentModel.Win32Exception at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams) at System.Windows.Forms.Control.CreateHandle() at System.Windows.Forms.Control.get_Handle() at System.Windows.Forms.Control.CreateGraphicsInternal() at System.Windows.Forms.ThreadExceptionDialog..ctor(System.Exception) at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception) at System.Windows.Forms.Control.WndProcException(System.Exception) at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)</Data> 
  </EventData>
  </Event>

**Comment by ghramsey** [comment]
It did happen again.   

I've been renaming the speech files in ` SOLACE` because they're named using text from the script 
and it's harder to follow them.  All seemed OK as I was scrolling through the list.  The silent CTD.

Application: CommandsEditor.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.ComponentModel.Win32Exception at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams) at System.Windows.Forms.Control.CreateHandle() at System.Windows.Forms.Control.get_Handle() at System.Windows.Forms.Control.CreateGraphicsInternal() at System.Windows.Forms.ThreadExceptionDialog..ctor(System.Exception) at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception) at System.Windows.Forms.Control.WndProcException(System.Exception) at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)

**Comment by MattFiler** [comment]
This is really hard to trace down 🤔

Please could you let me know:
- How long you've been using the script editor at this point
- If you've loaded multiple levels in the same session or just one
- What you were doing when it crashed (e.g. renaming an entity? etc?)
- When you say scrolling - were you scrolling through the entity's parameters or the list of entities in the composite?

Is this lag of drawing stuff something you see often?

**Comment by MattFiler** [comment]
I think this should hopefully now be fixed. Please let me know if it happens again!

**Comment by MattFiler** [comment]
I'm gonna close this one - but yeah please reopen if you encounter it again!

**Comment by ghramsey** [comment]
I'm not sure which bug it's related to. The nodegraph bug seems solved and it's misbehavior likewise has stopped.
I have three different similar bugs I reported so I'll add it on this one b/c it's related again to a silent crash.  
I'm not sure why this time.  I was scrolling through entities, but I didn't see anything acting slow this time.  

It was actually working great until it crashed.  Not sure if it's related. I'd just added a new speech entity before this.
I think the crash was as it was refreshing/repopulating the entitiy list.

Only details I have are again from windows event viewer because it was not trapped by Commands Editor.

Application: CommandsEditor.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled 
exception. Exception Info: System.ComponentModel.Win32Exception at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams) at System.Windows.Forms.Control.CreateHandle() at System.Windows.Forms.Control.get_Handle() at System.Windows.Forms.Control.CreateGraphicsInternal() at System.Windows.Forms.ThreadExceptionDialog..ctor(System.Exception) at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception) at System.Windows.Forms.Control.WndProcException(System.Exception) at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)

**Comment by MattFiler** [comment]
I've used the script editor extensively today and not encountered this problem - will leave this ticket open though for now.

If you encounter it again please try and capture what you were doing at the time of the crash 👍

**Comment by ghramsey** [comment]
I saw the exception again last night once, but before you pushed the 0.12 update.
I'll report if I encounter it again with this update.

Given your change log I have a feeling it's fixed though.

**Comment by ghramsey** [comment]
:notlikethis:  Sorry to say this darn bug has reared it's ugly head again.  Same issue as before scrolling through entities 
probably a little faster than the screen was drawing. It froze then crashed to desktop without error message.

Windows Event Viewer log:
=
Application: CommandsEditor.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.ComponentModel.Win32Exception at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams) at System.Windows.Forms.Control.CreateHandle() at System.Windows.Forms.Control.get_Handle() at System.Windows.Forms.Control.CreateGraphicsInternal() at System.Windows.Forms.ThreadExceptionDialog..ctor(System.Exception) at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception) at System.Windows.Forms.Control.WndProcException(System.Exception) at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)

**Comment by MattFiler** [comment]
Hmm yeah I'm at a bit of a loss here as I've not been able to replicate the issue locally & the error isn't particularly helpful. The fact that you're getting it in relation to a more general slowdown makes me wonder if it's just a lack of resources available on your machine, as I don't tend to get the lag you're mentioning.

If it happens again could you try keep an eye on task manager to see what % CPU/GPU are at? Additionally - do you have entity tabs enabled? Worth keeping on top of how many are active there if that's the case.

I have an idea of what it _could_ be outside of that, and I'll run you a build after work to see if it helps :)

**Comment by ghramsey** [comment]
I think this last time I had tabs off but this has happened with both on and off.    After that last crash opened what must have 
been 50 entities and nothing bad happened.   And I was scrolling through at warp speed.   Could it be a cache thing . ?  
Disk cache?   The program is on an NvME m.2 on my mainboard but maybe there's a bottle neck somewhere that happens suddenly.

**Comment by ghramsey** [comment]
I'll see if I can open taskmanager but I have only two monitors so it might not help to catch the event there...

**Comment by MattFiler** [comment]
I've pushed some changes in 0.12.0.1 (now live on main) which should hopefully fix this issue. If you get it again please let me know :)

**Comment by ghramsey** [comment]
No crashes so far though I've been playing the game; testing mostly  vs using editor.

Hopefully it holds.

I'm not sure if it's related and I might have mentioned it before when you made some changes:
speechscript entities populate really slow.  This evening they are the only hiccup when scrolling through entities.
But in the past when it hiccupped like that it would also sometimes be followed by crashes. 
That it is not crashing tells me you might have fixed the issue.

**Comment by ghramsey** [comment]
[-](https://github.com/MattFiler/OpenCAGE/issues/330#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/MattFiler/OpenCAGE/issues/330#) <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-04-25T18:22:25.8733156Z" /> 
  <EventRecordID>922695</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>ghram</Computer> 
  <Security /> 
  </System>
[-](https://github.com/MattFiler/OpenCAGE/issues/330#) <EventData>
  <Data>Application: CommandsEditor.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.ComponentModel.Win32Exception at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams) at System.Windows.Forms.Control.CreateHandle() at System.Windows.Forms.Control.get_Handle() at System.Windows.Forms.Control.CreateGraphicsInternal() at System.Windows.Forms.ThreadExceptionDialog..ctor(System.Exception) at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception) at System.Windows.Forms.Control.WndProcException(System.Exception) at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)</Data> 
  </EventData>
  </Event>

Got a random crash.  Sorry to say this bug seems to have recurred. 
Only once so hopefully isolated.

**Comment by ghramsey** [comment]
Application: CommandsEditor.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at System.Windows.Forms.NativeWindow.CreateHandle(System.Windows.Forms.CreateParams)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphicsInternal()
   at System.Windows.Forms.ThreadExceptionDialog..ctor(System.Exception)
   at System.Windows.Forms.Application+ThreadContext.OnThreadException(System.Exception)
   at System.Windows.Forms.Control.WndProcException(System.Exception)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr, Int32, IntPtr, IntPtr)
  =
[-](https://github.com/MattFiler/OpenCAGE/issues/330#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/MattFiler/OpenCAGE/issues/330#) <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2024-10-11T23:55:39.3699908Z" /> 
  <EventRecordID>1003666</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>ghram</Computer> 
  <Security /> 
  </System>
[-](https://github.com/MattFiler/OpenCAGE/issues/330#) <EventData>
  <Data>CommandsEditor.exe</Data> 
  <Data>0.2.0.0</Data> 
  <Data>c6f3f7b3</Data> 
  <Data>KERNELBASE.dll</Data> 
  <Data>10.0.19041.4957</Data> 
  <Data>c5225d0f</Data> 
  <Data>e0434352</Data> 
  <Data>000000000003b699</Data> 
  <Data>3528</Data> 
  <Data>01db1c23a099cf00</Data> 
  <Data>D:\SteamLibrary\steamapps\common\Alien Isolation\DATA\MODTOOLS\REMOTE_ASSETS\scripteditor\CommandsEditor.exe</Data> 
  <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
  <Data>67a722a6-885c-473a-a033-05308e030086</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
   
Silent crash again. This report might be moot with your up coming changes, but in case it means 
something and you'd said let you know if it cropped up again.

Scrolling through a very large entity; one of the cage animations in M7.  
Took a bit, hung and then poof to desktop. No error message.
