### ISSUE TITLE
The Asset Editor "Extract All" uses seemingly legacy file explorer

### ISSUE THREAD

**Issue by ProjectHSI** [MattFiler/OpenCAGE#332]
Can you please use the explorer instead please? If this is meant to be fully cross-platform then maybe I can understand and if that's so please tell me, but otherwise could you please use the explorer instead?

**Comment by MattFiler** [comment]
Extract all uses the folder picker rather than file picker, which makes the most sense in that context.

**Comment by ProjectHSI** [comment]
If that's so, can you provide the option to manually specify the folder path? It's slightly annoying to traverse the file system with.
