### ISSUE TITLE
New entity creation opens two tabs

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#334]
Created a new entity and it changes the first tab to the created entity and creates a duplicate tab.
As noted on the nodegraph ticket.  No crashes and the stability seems better with the tabs being drawn at 
same rate as selection, but this latest update now only creates two tabs at a time which cycle back and forth
as entites are open.   I  figured this might be as intended and it seems to work OK.  Maybe this tab duplication
 is related to that change though?  I'm sorry to keep you so busy with UI problems

**Comment by MattFiler** [comment]
Fixed in latest staging update!
