### ISSUE TITLE
'Go To Link' button does not work if search bar is populated

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#349]
Go To Link button is not working on some entities since the update.
No crash but the buttons do not work. Happening on both pin in and pin out buttons.

It seems to work on some entities, but mostly it does not.

**Comment by MattFiler** [comment]
I'm not able to replicate this - do you have any context? Which level, composite, entity, and link are you trying this on?

**Comment by ghramsey** [comment]
It's linked to the search bar.  Looks like if the search bar is populated the link buttons refuse to work.

I made a quick video clip so you can also see my settings:
https://github.com/MattFiler/OpenCAGE/assets/51859157/f93ab60a-7bd4-4575-aa56-d2379f516be4

**Comment by ghramsey** [comment]
Let me know if that link worked ar your end.  I does not work for me to test it.

**Comment by MattFiler** [comment]
Ooh good spot. Will get a fix out for this today :)
