### ISSUE TITLE
Steam deck?

### ISSUE THREAD

**Issue by RaptorKush420** [MattFiler/OpenCAGE#359]
Can someone explain to me like I’m 5 how to get openCAGE to work on steam deck?

**Comment by MattFiler** [comment]
Hey - this would be better placed in Discussions or on Discord.

If you're using a Windows OS on the Steam Deck then you should be able to install and run OpenCAGE as explained in the readme. If you're using a Linux distro I can't imagine you would have much luck - I've not tried using Wine or anything similar.

It's also worth noting that the Linux version of Isolation itself is not fully supported by the mod tools as it uses a different level format to the versions found on Steam/GoG/Epic.
