### ISSUE TITLE
Display already added parameter types in new "Add Parameter" window as disabled

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#361]
In the new add paramter window ENUM data types are not listed.

This is a CMD_GoTo entity and  in this instance the Move_Type which is an ENUM is not there,

![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/de0f4481-a5db-41a7-b9cb-27890428e922)
![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/55d2f5db-6667-4ae4-a3a0-1271ba5dd2ab)

I did a little digging to other entities such as doors and those too are missing ENUM data types from add parameters list.

*edit* OH.  also tried searching the list for move in case it just was not listed.  It doesn't show in search either. *end edit*

**Comment by MattFiler** [comment]
Parameters that are already applied to the entity will not show up in that list (as you can't add the same parameter twice). Just checked a CMD_GoTo with no parameters added and the `move_type` enum parameter does correctly show in the list.

![image](https://github.com/MattFiler/OpenCAGE/assets/6270995/46c7b9a4-3a5a-4011-9304-b8ad17365347)

So while this isn't a bug, perhaps I should change the UI to better communicate that some options are emitted?

**Comment by ghramsey** [comment]
Yeah. I just caught what you did there while expermenting with a new cmd_goto also.
The list box is more efficient to only show parameters which are available for use.

And what you say makes sense. Show it as disabled where appropriate.    
I like the list box though in this more compact form too.
