### ISSUE TITLE
Cortex XDR Issue

### ISSUE THREAD

**Issue by HavocGame** [MattFiler/OpenCAGE#363]
Dear @MattFiler ...

I have been having Issues with OpenCAGE, When I open OpenCAGE It is blocked by Cortex XDR, now I do not know how this program is on my Device but to my knowable Cortex XDR is on all window machines It's a anti malware software. So that means there's a File in OpenCAGE that's causing Issues. Now that is not a problem because normally, I would be able to have an option that allows me to "Run Anyway" but when I pressed that button it showed: 
![image](https://github.com/MattFiler/OpenCAGE/assets/168385249/a6ae294a-6098-4e88-86e7-32ad4565783d) 

Now in the company or whatever it says that Anything with .exe is blocked or at least close to those lines. And never did I install Cortex XDR, but I have had a story issue with this program such as trying to run mods on Half-Life 2 or 1 7 years ago. and I have tried to disable/Uninstall the whole software, but it says I need administer, that's something I do not know how to obtain. So please @MattFiler Help me get OpenCAGE.

Thanks Havoc....

**Comment by MattFiler** [comment]
If Cortex is antivirus (seems to be so), you should be able to whitelist the Alien: Isolation folder to get it to ignore OpenCAGE :)
