### ISSUE TITLE
Tab does not update composite name when using GO button 

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#370]
This may be a limited case.  Going from the instanced NPC_LOGIC_1 inside on of the NPC composites via the GO Button 
returns to the ARCHETYPES/Misc_subarchetypes/NPC_LOGIC compostite, but the tab does not update to reflect it.

![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/850dfb50-ad4a-4d4a-a9af-e32e04ef7cd5)

It continues to show the name of the composite I began in with the instanced composite.
![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/b108e97c-8268-49d2-8fad-4ea7a771ab41)

I have not tested this extensively.  It may be limited here or global.

**Comment by MattFiler** [comment]
This is intentional behaviour - you're entering a composite instanced inside the previous composite (as you can see by the path at the bottom of the screen), so the tab title remains that of the first composite in the path.

**Comment by MattFiler** [comment]
When more of the instance mode stuff is implemented I'll add some additional info into the docs to make this clearer. Still working on it at the mo :)

**Comment by ghramsey** [comment]
OK.  I see what you mean now.   
I know you have heaps of work to do.
