### ISSUE TITLE
Texture editor crashes when importing non-DX10 DDS images

### ISSUE THREAD

**Issue by E11NTM** [MattFiler/OpenCAGE#373]
I've been trying to replace a texture in the asset editor, but when trying to replace it, it gives me the following error.

System.NullReferenceException: Reference to object not established as an instance of an object. In AlienPAK.CathodeLibExtensions.ToTEX4Part(Bytecontent, TextureFormat& format, Part part) in AlienPAK.Explorer.ReplaceSelectedFile()

This happens with any texture I try to replace which makes the texture editor unusable.

**Comment by MattFiler** [comment]
Hey, please could you give some more detailed information regarding the level you're editing, if you have made any edits previously, specifically what texture you're trying to modify, and include the file you're trying to replace it with?

Thanks :)

**Comment by E11NTM** [comment]
Sure! I was trying to change in DLC_SalvageMode1 the fx_flame_thrower_ribbon to this file: 
![fx_flame_thrower_ribbon](https://github.com/user-attachments/assets/9a1b3d63-304e-4383-aa9f-cb2f84d7d85b)
By the way I used an online conversor to transform it into DDS here's the conversor: https://convertio.co/es/dds-png/
If you need the DDS file because it might be a problem of the conversion or something I could send it to you in Discord, but GitHub doesn't allow me to send DDS here.

**Comment by MattFiler** [comment]
Ah, so this is an issue with the tools not giving a good enough error message. You're converting to DDS but not the right DDS format.

You'll want to be using DX10 DDS images for Isolation. I would recommend converting your image using something like Nvidia's [Texture Tools Exporter](https://developer.nvidia.com/texture-tools-exporter).

**Comment by MattFiler** [comment]
Just pushed a fix to warn about non-DX10 headers. It will be in OpenCAGE within the next update 👍 
https://github.com/OpenCAGE/AssetEditor/commit/427902742c438d2877f47878959b03027c4fdbc0

**Comment by E11NTM** [comment]
Ohhh Alright thank you very much!

**Comment by MattFiler** [comment]
Will close when the update is pushed out :)
