### ISSUE TITLE
Seemingly wrong texture content when exported by Asset Manager

### ISSUE THREAD

**Issue by Paul-BravoZulu** [MattFiler/OpenCAGE#378]
I did several successive exports of the texture **base.tga** in DATA\ENV\PRODUCTION\DLC\BSPNOSTROMO_TWOTEAMS\RENDERABLE\LEVEL_TEXTURES.ALL.PAK. The first export of **base.tga** was good, ie with alpha and colour (see attached file ![base_working](https://github.com/user-attachments/assets/67c28d8e-cb81-40b4-b0ff-2ffa47cfd694) but successive exports are totally blank (flat #ffffff on the whole image see : 
![base](https://github.com/user-attachments/assets/860982ab-f377-43d8-84bb-a5ab0d4559e5) ).

I have not managed to find a consistent scenario to reproduce the bug and export this specific texture correctly.

**Comment by MattFiler** [comment]
As far as I can tell, `base.tga.dds` is just a white texture that's 484 bytes in size. I'm not sure how you achieved the results in the attached file, but it appears like that file is incorrect.

I've just tried exporting using the DDS/PNG/JPG options on BSPNostromoTwoTeams and have run in to no issues 🤔
