### ISSUE TITLE
Update loop when OpenCAGE not contained inside A:I folder

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#393]
I have one version of opencage on my desktop for the EGS version of the game.

Upon launch for the update today (11/30) it seemed to proceed normally, 
but then it looped and restarted the update again and again.

I killed the process and the updater exe remained on the desktop and must have had a file handle open
since window reported it in use.  I restarted my system to fix that and that's not unusual when killing a process.

Anyway, I placed the program into the EGS A:I folder and the update worked normally.

**Comment by MattFiler** [comment]
After a reboot did the update loop fix itself?

**Comment by MattFiler** [comment]
Ooh actually I'm seeing the same behaviour - thanks for reporting. I'm out today but will take a look at this tomorrow.

**Comment by MattFiler** [comment]
Ah - just noticed the issue - I hadn't correctly rebuilt the updater embedded within OpenCAGE.

A fix has been pushed to staging but the problem may reoccur until the update is pushed to main.
