### ISSUE TITLE
Experimental Tools no longer available?

### ISSUE THREAD

**Issue by MarioMarietto** [MattFiler/OpenCAGE#41]
Hey there,
Today I downloaded OpenCAGE and while I was checking the Wiki I noticed the: "Editing keycodes & Editing text" tools. I saw that there should be an "Experimental Tools" window, but I can't find it. They have both been removed or they're not an experimental feature anymore? If they're still available, where I can find them?
Thanks

**Comment by MattFiler** [comment]
Keycodes can now be edited using the script editing tools so that functionality was removed - the localisation editor will return in a future update :)

Will update the Wiki to reflect that!

**Comment by MarioMarietto** [comment]
> Keycodes can now be edited using the script editing tools so that functionality was removed - the localisation editor will return in a future update :)
> 
> Will update the Wiki to reflect that!

Perfect, thanks!
