### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by antopilo** [MattFiler/OpenCAGE#46]
Hey, just wanted to know if you were still working on this. 
Ill would be willing to contribute on the project. Especially on the level editing aspect.
Is there a discord server, etc, etc..

**Comment by MattFiler** [comment]
Yeah, I'm still working on this project around other commitments. 

The level editor is making some progress over on the [CathodeEditorUnity](https://github.com/OpenCAGE/CathodeEditorUnity/tree/test) repo, it'll be included into the main repo when it's more feature complete!
