### ISSUE TITLE
Character Spawning

### ISSUE THREAD

**Issue by Aniruddh-J** [MattFiler/OpenCAGE#52]
Hello,

First off, a huge thanks to Matt for developing this awesome tool. 

I have been trying to find a way to spawn hostile Androids and NPCs in certain missions. I am, however, not able to figure out the way to spawn them. 

Also, sorry for posting this as an issue. I was planning to open this in the discussion area but that area is almost dead so I thought to open this topic here.

**Comment by MattFiler** [comment]
Hey - the way to achieve this is to use the Cathode Script Editor in the staging branch of the tool.

To enable the staging branch, click on the cog in the main OpenCAGE window and tick "recieve updates from staging branch".

When in the Script Editor, navigate to the mission script you want, click Add Entity, and add a flowgraph entity for Android.

Link up the spawn event on the Android to the trigger you want it to be (maybe make a PlayerTriggerBox function to trigger it).

Done!
