### ISSUE TITLE
Braniac Designer > Export behavior dialog box size issue

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#53]
![image](https://user-images.githubusercontent.com/51859157/151710101-078e47f5-9c9d-4bdd-b73b-b74060811461.png)

The export behaviors box is smaller than it should be.  Cannot see the entire window.  
I can manage to hit one or the other barely but it is not acting as intended even then.

**Comment by ghramsey** [comment]
Additionally the scroll bar does not function nor does the note that is selected show correctly.

**Comment by MattFiler** [comment]
Thanks for the spot, will update this in the next release.
