### ISSUE TITLE
Launch game option with Epic store version; failed to launch- game running issue

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#61]
![image](https://user-images.githubusercontent.com/51859157/159638322-cf9b3010-38c9-470c-90d1-a7fd14d74342.png)

This is on Epic Store version of Alien Isolation.  I've restricted my mod use to that version.

The game launches normally from it's exe or epic library. When I tried to launch game option on opencage it seems nothing happens.
I twice or more and still nothing.  I killed the epic launcher and restarted it's background service.  Tried again.  Nothing.
Then I got thewindow shown on the screenshot.   Monitoring task manager when I tried to launch it the AI.exe opens for a moment then disappears .  After a delay the launcher message window appears.

I tried to make the screenshot so let you see the options I used and the TM.  

I think the issue is in one or more of the options I selected.
But I don't know which one.

Also, not sure if it's pertinant, but I have ReShade installed.

**Comment by MattFiler** [comment]
Interesting. Have you tried restarting your PC and launching the game from OpenCAGE again? Starting up on EGS does take some time as you have to wait for all their services to initialise, so perhaps you tried again a bit too soon?

Either ways I'll add some validation to this later. Cheers!

**Comment by MattFiler** [comment]
Tried replicating this myself and haven't had any luck. OpenCAGE prevents you from launching two instances of the game at once itself, so this issue should never occur.

Out of interest, do you have OpenCAGE in your A:I folder? Could you try copy the exe into a different folder & see if that resolves the issue?

Alternatively, try a restart without moving the OpenCAGE exe and see if that resolves the problem. EGS is nutoriously slow/buggy to launch apps, so something could be stuck in a background process.

**Comment by ghramsey** [comment]
After I posted here.  I opened and closed AI a few times normally and it worked.   It also seemed to open depending on which option I checked and unchecked.

I was going to make a short vid clip so it would be better illustrated the delay and to my surprise the issue has vanished.
Launch immediately opened the game without delay.    
I didn't restart the computer so I don't know what transpired that it's working.  I guess the issue is closed.

**Comment by MattFiler** [comment]
Hmm interesting, I'll test a bit more extensively this evening - but in the meantime let me know if it returns!

**Comment by ghramsey** [comment]
So, I been having

**Comment by MattFiler** [comment]
Thanks for reopening the ticket with this extra info! I'll explore some options.

**Comment by ghramsey** [comment]
Are there any log files from either Epic , Cage or AI that can be turned on that could help.  EPS launcher has debug log option.

This is minor honestly except if it stops cage from triggering AI to load which it does per my orignal post in March.

**Comment by MattFiler** [comment]
Closing this as I've had no other reports.

**Comment by ghramsey** [comment]
EPIC launcher is still a stupid POS.     

Now any use of the Open Game option causes the game to instantly hang and crash.
And once that has happened the game will no longer start even after closing EPS launcher and restarting it.

This has been happening now for a while though, not related to the update.
I've tried both staging and master branches too.

Fixng EPS is starting to seem like a Sisyphus Myth.

**Comment by MattFiler** [comment]
I'll investigate that further, perhaps there's a bug with OpenCAGE's game launcher that hadn't previously been exposed. I patch some stuff in the game binary that uses different offsets between Steam/Epic/GoG so it's possible it's my fault.

**Comment by MattFiler** [comment]
Just tried it out, working fine for me! Perhaps you've modified something that's causing the crash?

**Comment by ghramsey** [comment]
That's strange.  

I've verified the game multiple times.  And the only thing that cures the issue once the open game option
is used is verifying the game.  I'm not re-installing it anew though. 
So maybe there is a file or files which are remaining that the verify function does not change.  

I cannot fathom why that would be, but I'll try something new a full uninstall-reinstall.
I don't remember last time I've done that.  I'm going to also delete the cloud-saved game files too.
That should be a clean installation without any doubt.

**Comment by ghramsey** [comment]
I uninstalled (the EGS uninstaller wiped the entire folder out to my dismay) , 
also removed all the files in the cloud save folder and re-installed.

I placed opencage on my desktop, ran it and pointed it to the AI.exe in the folder.

It updated (master branch), and I tried to use the open game option.  Same result as before.
The window tries to open something and then closes immediately w/o error.

And after that AI refuses to launch with EGS reporting "running" for several minutes after 
the attempt, but it's crashed. Then the EGS launcher window will refresh flash the task bar.

AI then refuses to launch anymore even with a restart of EGS launcher.  
:shrug:  I have no clue what's going on with this.

**Comment by ghramsey** [comment]
Yes.   If I verify the game it launches fine from EGS launcher.

If I use OpenCAGE to launch the game it stops working and the game misbehaves as noted above
 even if I only launch from EGS launcher.
 
 And this is all after a full uninstall (which removes the entire folder tree) and reinstall.
