### ISSUE TITLE
Making any change to ENG_REACTORCORE or ENG_TOWPLATFORM with 9.2.5 breaks visual effects.

### ISSUE THREAD

**Issue by mc68k** [MattFiler/OpenCAGE#69]
I'm not sure what's causing this, but here are steps to reproduce:

1.  Open original ENG_REACTORCORE into the script editor.
2.  Open SCRIPT_STORYMISSION->M25_ROCK_BOTTOM->M25_PART_03
3. In the Entities search box type _rip_ and hit search.  That's UNDERSCOREripUNDERSCORE.
4. In the first item A1_M2501_RIP_8804 change the sound event parameter to A1_G0000_RIP_0010D and save.
5. Run map.  The following effects are now broken:  

The increase of discharge speed as you reset cores.
The additional fog effect that appears before the new androids burst into flame.
The electric discharge rings when the core is purged.

Other than that, the script seems to play out as intended.  This issue wasn't present in earlier OpenCAGE versions, which I used to create a mod restoring some cut dialog.  I can't find this version in my backups, but it would've been the version available for  download close to June 03, 2021.

Original .pak size: 5,353,472 bytes
Modded .pak size (with above change only): 5,365,760 bytes

Save files for quick testing:  https://drive.google.com/file/d/1TNfkPTY7mOj81NP6OQh8a9un5w9Nm-UO/view?usp=sharing

**Update:**  Making any change to ENG_TOWPLATFORM breaks all fire effects and some lighting (the stairway to the upper control room).

Edit:  Did a deep dig on backups and found 9.0.3.  Same issue.

**Comment by MattFiler** [comment]
Thanks for the report!

**Comment by MattFiler** [comment]
Thanks for the report!

Any chance you could capture a before & after video? I've been unable to replicate these issues by making the edits myself.

There were some changes introduced in 9.2.4 which makes the script editor automatically clear out garbage data, so it's possible that I'm auto-deleting something that's in-use. If you're testing with 9.0.3 OpenCAGE will auto update the script editor for you to the version in 9.2.5, so it's probably not present in that version but you're just getting the update come through.

**Comment by mc68k** [comment]
M18 comparison video:
https://youtu.be/fRazF7axYwA


M18 edited pak file that produced the edited results in video: 
https://drive.google.com/file/d/1-YMENBVMAatqQhwXqUiTlPA0m-HQiUWy/view?usp=sharing

Reactor core will take a bit to make, stand by.

**Comment by MattFiler** [comment]
That video was super helpful, thanks!

I've just pushed an update to the staging branch which should hopefully resolve this issue. Please could you swap to staging and give it a test for me?

From the main OpenCAGE window, click the cog, then tick "Recieve updates from staging branch".

**Comment by mc68k** [comment]
The 9.2.6 staging version fixes the bug.  All missing visuals are now present in ENG_REACTORCORE and ENG_TOWPLATFORM with 9.2.6.  Very quick work.  Thank you so much.  I'm off to make a donation.

**Comment by MattFiler** [comment]
Very kind, thanks! I'll get this merged down to main.
