### ISSUE TITLE
"Page took too long to render" - Cannot view wiki

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#75]
![image](https://user-images.githubusercontent.com/51859157/180877293-c17b2cd5-30c6-41f9-a0dd-16aa045e2645.png)

I'm getting a wiki error when I clicked a link on your wiki page about the cathode script editing:
=================
Loading a script

To edit a script, launch the editor by going to "Experimental Tools" > "Edit Cathode Scripts". You can then select a level from the game in the dropdown in the top left and press "Load".

All flowgraphs (scripts) will be displayed in the hierarchy on the left hand side of the toolset.

Select a script and you will then see all of the nodes contained within that flowgraph. Nodes are displayed with their name, and their type in brackets after. To view all available node types,  _[click here](https://github.com/MattFiler/OpenCAGE/wiki/Cathode-Nodes)._

You can select each node to load up its parameters and links. Imagine the UE4 Blueprint interface when thinking of node child/parent links - parent links come in to the node on the left hand side, and child links go out on the right.
================================

This link generates a page to large to render wiki error:

 _[click here](https://github.com/MattFiler/OpenCAGE/wiki/Cathode-Nodes)._

**Comment by MattFiler** [comment]
Yeah this is a known issue, pages are rendered locally so if your PC isn't beefy enough it'll time out. If you refresh a few times it should eventually load :)

To solve this issue, I'll look at adding the node info to the opencage.co.uk website.

**Comment by ghramsey** [comment]
Thank you.  I'm using firefox on a year old I7-9700F with 16GB RAM and a GTX 1660 GPU.
Should be beefy enough for anything in a browser.  

It's loading OK now.      
If you did that check to the node info you seem to have fixed it.
Thank you again.
