### ISSUE TITLE
Enhancement - Method to ID multiple OpenCage instances; read-only option

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#77]
I have unmodified Steam AI and modified EGS.   I have an opencage install on each folder.
I want to use opencage on each version to say view the vanilla script of Steam and compare where in the 
modified script changes were made so I can better understand how such changes are created.   

Is there some way to ID each instance?  As it is now.  If I have two cathode editor windows side by side it's 
easy to lose track of which window is for which because windows will overlap them and I lose the order. 

I don't want to modifiy the files of Steam.  So I'd love some method to ID one instance over the other.  
Even a read-only check box that would show on the window title would probably work for this and 
maybe not be too hard to impliment?   It's not super critical but maybe in some future update this would be nice.

Another possible idea?
Maybe easier to implenment (?) is state the game platform in the title.  Since I'm reading steam and egs at same times.

**Comment by MattFiler** [comment]
Nice user feedback, thanks! I'll look at getting this into staging shortly.

**Comment by ghramsey** [comment]
Cool.  I was not sure how easy these ideas would be. Thank you.

**Comment by MattFiler** [comment]
Sorry for the delay on this one - this functionality is now on the staging branch! Tick "show game platform in script editor" within OpenCAGE's settings window to enable it.

**Comment by ghramsey** [comment]
Thank you
