### ISSUE TITLE
"A new version of OpenCAGE is available" loop

### ISSUE THREAD

**Issue by johnl-m** [MattFiler/OpenCAGE#79]
**Reproduction steps**: 
1. Download the latest version (0.9.2.8) of OpenCAGE from https://github.com/MattFiler/OpenCAGE/releases/tag/0.9.2.8
2. Click "Edit Configurations"
3. Receive 
![image](https://user-images.githubusercontent.com/24286589/188490097-7e063470-50aa-4c67-9c0d-7e04ec7c37f1.png) error message (note this particular screenshot is using the staging release, but the behavior is the same with master)
4. Click OK, updater tries to download a new version of OpenCAGE (ends up with the same executable)
5. Repeat, cannot use tool

**Additional Information**:
I'm not sure what's going wrong here. Even when I disconnect the internet connection, I still get prompted to update, and can't find a way to disable this behavior.

I'm able to reproduce this under Wine in Linux, as well as a new Windows 11 VM

**Comment by MattFiler** [comment]
Hey, please check that your Alien: Isolation directory is writable - this process is downloading the OpenCAGE components into your A:I directory, so it's possible that it's failing to write to the DATA folder.

Additionally - where is your OpenCAGE.exe located? Is it in the game root?

**Comment by johnl-m** [comment]
Hi, thanks for the suggestions! 

* I have OpenCAGE.exe in my game root, at `C:\Program Files (x86)\Steam\steamapps\common\Alien Isolation\OpenCAGE.exe`
* `C:\Program Files (x86)\Steam\steamapps\common\Alien Isolation\` is writable. 

It's weird, OpenCAGE is able to successfully create asseteditor, legendplugin, and scripteditor within `C:\Program Files (x86)\Steam\steamapps\common\Alien Isolation\DATA\MODTOOLS\REMOTE_ASSETS`. The tool then deletes the updater, and relaunches itself. But the `configeditor` directory is missing, along with `cinematictools`.

Anyway, as a workaround, I was able to manually download https://raw.githubusercontent.com/OpenCAGE/AlienConfigEditor/master/Build/AlienConfigEditor.exe into REMOTE_ASSETS/configeditor, and now everything's working as it should. Totally possible this was just an issue with my VM hard drive setup or something.

**Comment by MattFiler** [comment]
Good to hear, thanks for the follow up. I will investigate potential causes, but glad you've got it sorted in the meantime. 

If you encounter the issue again with any future updates, please re-open and I'll bump up the priority!
