### ISSUE TITLE
"Failed Lookup! Encountered an issue while looking up entity Please report this on GitHub" message

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#81]
Got this error which states to report it so I am.

![Untitled](https://user-images.githubusercontent.com/51859157/198454067-f9f909bb-1950-43ab-a324-08bf8e911036.gif)
I was actually just viewing an unedited file on steam and it threw this error. I checked EGS and it does it there too.

**Comment by MattFiler** [comment]
Thanks for the report! This is fixed in the next release, which should be out soon. I'll leave this ticket open in the meantime :)

**Comment by ghramsey** [comment]
Just realized something that is probably important.  
I was using the staging branch and it throws that bug.  But the master branch does not.

**Comment by MattFiler** [comment]
Closing this as it's fixed in the impending release.
