### ISSUE TITLE
Enhancement - triggerbox parameter name 'position' is case senstive, add typo trap?

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#83]
I made a triggerbox copied from another person's mod, but I made a single typo. 
I typed 'Position' instead 'position' and the triggerbox failed to work in game.   
It was someone who was comparing the two files side by side that caught the issue.   
I had to delete the triggerbox position and recreate it but once done now it works.

Any chance you could add a trap for this sort of typo mistake?  
A prompt or perhaps auto correct it since it must be lower case?

In lieu of a trap can you add some way to more easily edit the parameter name?  
Deleting the triggerbox position and retyping the coordinates was tedious.
 
Thank you

**Comment by MattFiler** [comment]
Easier editing of parameter names is a nice suggestion. For future reference, when you add new parameters to an entity, that textbox has a dropdown which shows some supported parameter names - `position` should have been listed there!

**Comment by ghramsey** [comment]
The New parameter dialog shows Data type POSITION and has a drop down list with named data types that is fixed:
![image](https://user-images.githubusercontent.com/51859157/203439385-7ccfb5db-0e55-4076-b082-9ed4d68c6fd8.png)
The Param Name field is a text box and position is not on the list: 
![image](https://user-images.githubusercontent.com/51859157/203439338-9b259971-19ae-42fe-bb79-2f00f655ef13.png)
