### ISSUE TITLE
question : how to remove this artifact?

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#84]
I changed a door from being hackable to using a handle.  
That works fine. The door opens, but the graphic to enter the code remains floating as the door opens past it.
Specifically the door I changed is the one you get the code 0482. Tech_hub transit office.

![AI 2022-11-27 01-20-32](https://user-images.githubusercontent.com/51859157/204125456-b382d69e-f0a7-4fbb-909b-7fbbe9b449f0.png)

**Comment by MattFiler** [comment]
This is addressed in the upcoming release via support for editing instanced movers.
