### ISSUE TITLE
Resource editing disabled on DLC

### ISSUE THREAD

**Issue by ttvjeffnl** [MattFiler/OpenCAGE#91]
Resource editing disabled on DLC Maps:

BSPNOSTROMO_RIPLAY_PATCH
BSPNOSTROMO_TWOTEAMS_PATCH

![1](https://user-images.githubusercontent.com/68294929/209438922-8f06d1e9-8a85-4f48-9d69-70e49d3dd99e.png)
![2](https://user-images.githubusercontent.com/68294929/209438924-284d3146-43d6-4728-b1bf-f211f0e1c738.png)

**Comment by MattFiler** [comment]
This is due to the _PATCH extension on the filepath. Will push a fix to staging shortly.

**Comment by MattFiler** [comment]
Please re-launch OpenCAGE and switch to the `staging` branch in settings. This should now be fixed!

**Comment by ghramsey** [comment]
![image](https://user-images.githubusercontent.com/51859157/209475708-ba8e93d3-d78e-4010-81c2-b64f533adacf.png)
Had same issue this morning.  Version is staging 0.9.3.01.    I think I grabbed the update after this error was initially reported.

I think it may be related to changing files in the folder when the script editor is open.  I dropped a different commands.pak 
file over the file I had opened.  I hit reload and it threw the error. Also hitting OK seemed to continue loading the file though

**Comment by MattFiler** [comment]
@ghramsey Interesting - which map were you editing with those steps when you saw this message? Have you deleted any RENDERABLE files in that map?

**Comment by ghramsey** [comment]
I opened I think Tech_Comms or Tech_Hub. 
I believe as I said above it was when I overwrote an already open file with a vanilla unaltered file.

**Comment by MattFiler** [comment]
@ghramsey Thanks for the info - I've managed to replicate it, and it's a separate issue to Jeff's. I'll take a look.

**Comment by ghramsey** [comment]
OK.  Glad it's reproducable.   Given it was same message box I thought it was same problem.
