### ISSUE TITLE
[enhancement] simple 'undo' function

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#98]
I'm not sure how hard or simple this might be to add.  I bet an actual real time undo is hard or you'd have implemented it already.

How about save a backup on a timer every 1-5 min and let it be selectable like some word processors do?
OR how about just a .bak file created at each save as a rudimentary undo.   

Anything is better than remembering to save a backup in case the changes break something

**Comment by MattFiler** [comment]
This would be great to add at some point when I start properly improving the interface - thanks for the suggesion.

**Comment by MattFiler** [comment]
I'm pushing an update to the staging branch shortly which adds the option for an automatic backup every 5 minutes :)

**Comment by ghramsey** [comment]
Excellent! Thank you.
